# Phonepe project

Step 1 :Installations

In [2]:
!git clone https://github.com/PhonePe/pulse.git

fatal: destination path 'pulse' already exists and is not an empty directory.

In [3]:
import os
import json
import pandas as pd

Step 2 : Creating tables

In [4]:
# Path to the aggregated insurance data
Agg_ins_state_path=r"C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state"
Agg_state_list=os.listdir(Agg_ins_state_path)

#initialize columns for the dataframe
agg_ins_data={'State':[],'Year':[],'Quarter':[],'Transaction_type':[],'Transaction_count':[],'Transaction_amount':[]}

#using for loop to extract the path
for state in Agg_state_list:
  years=os.listdir(f"{Agg_ins_state_path}/{state}")
  for year in years:
    quarter=os.listdir(f"{Agg_ins_state_path}/{state}/{year}")
    for qtr in quarter:
      # Check if the entry is a json file
      if qtr.endswith('.json'):
        path=f"{Agg_ins_state_path}/{state}/{year}/{qtr}"
        print(f"Processing file: {path}")

        #loding json file
        try:
          with open(path,'r') as f:
             data=json.load(f)
          #print(data)

          #extracting data
          for i in data['data']['transactionData']:
             insurance=i['name']
             count=i['paymentInstruments'][0]['count']
             amount=i['paymentInstruments'][0]['amount']
             print(insurance,count,amount,state,year,qtr)

             agg_ins_data['State'].append(state)
             agg_ins_data['Year'].append(year)
             agg_ins_data['Quarter'].append(int(qtr.strip('.json')))
             agg_ins_data['Transaction_type'].append(insurance)
             agg_ins_data['Transaction_count'].append(count)
             agg_ins_data['Transaction_amount'].append(amount)

        except KeyError:
            print(f"Skipping file due to missing keys: {path}")
        except FileNotFoundError:
            print(f"Skipping file not found: {path}")
        except Exception as e:
            print(f"An error occurred while processing {path}: {e}")

#creating dataframe
agg_ins_df=pd.DataFrame(agg_ins_data)

agg_ins_df["State"]=agg_ins_df["State"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar Islands')
agg_ins_df["State"]=agg_ins_df["State"].str.replace("-"," ")
agg_ins_df["State"]=agg_ins_df["State"].str.title()
agg_ins_df["State"]=agg_ins_df["State"].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')

agg_ins_df

Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2020/2.json
Insurance 6 1360.0 andaman-&-nicobar-islands 2020 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2020/3.json
Insurance 41 15380.0 andaman-&-nicobar-islands 2020 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2020/4.json
Insurance 124 157975.0 andaman-&-nicobar-islands 2020 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2021/1.json
Insurance 225 244266.0 andaman-&-nicobar-islands 2021 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2021/2.json
Insurance 137 181504.0 andaman-&-nicobar-islands 2021 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2021/3.json
Insurance 230 305235.0 andaman-&-nicobar-islands 2021 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2021/4.json
Insurance 757 1056380.0 andaman-&-nicobar-islands 2021 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2022/1.json
Insurance 768 1131287.0 andaman-&-nicobar-islands 2022 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2022/2.json
Insurance 501 779740.0 andaman-&-nicobar-islands 2022 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2022/3.json
Insurance 643 902466.0 andaman-&-nicobar-islands 2022 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2022/4.json
Insurance 901 1441210.0 andaman-&-nicobar-islands 2022 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2023/1.json
Insurance 1004 1439198.0 andaman-&-nicobar-islands 2023 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2023/2.json
Insurance 768 1233395.0 andaman-&-nicobar-islands 2023 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2023/3.json
Insurance 795 1251145.0 andaman-&-nicobar-islands 2023 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2023/4.json
Insurance 1145 1757821.0 andaman-&-nicobar-islands 2023 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2024/1.json
Insurance 1371 1964556.0 andaman-&-nicobar-islands 2024 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2024/2.json
Insurance 1097 1744694.0 andaman-&-nicobar-islands 2024 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2024/3.json
Insurance 1191 1752800.0 andaman-&-nicobar-islands 2024 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andaman-&-nicobar-islands/2024/4.json
Insurance 1293 2026380.0 andaman-&-nicobar-islands 2024 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2020/2.json
Insurance 22104 3982391.0 andhra-pradesh 2020 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2020/3.json
Insurance 49812 12426481.0 andhra-pradesh 2020 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2020/4.json
Insurance 21464 12985632.0 andhra-pradesh 2020 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2021/1.json
Insurance 22105 12749874.0 andhra-pradesh 2021 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2021/2.json
Insurance 33205 22730687.0 andhra-pradesh 2021 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2021/3.json
Insurance 23075 19914338.0 andhra-pradesh 2021 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2021/4.json
Insurance 25423 31610335.0 andhra-pradesh 2021 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2022/1.json
Insurance 29954 42648157.0 andhra-pradesh 2022 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2022/2.json
Insurance 32185 41708072.0 andhra-pradesh 2022 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2022/3.json
Insurance 39301 48791931.0 andhra-pradesh 2022 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2022/4.json
Insurance 44329 58043239.0 andhra-pradesh 2022 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2023/1.json
Insurance 34920 51963355.0 andhra-pradesh 2023 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2023/2.json
Insurance 36376 52067478.0 andhra-pradesh 2023 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2023/3.json
Insurance 43150 57802396.0 andhra-pradesh 2023 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2023/4.json
Insurance 41798 62342423.0 andhra-pradesh 2023 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2024/1.json
Insurance 46582 63563802.0 andhra-pradesh 2024 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2024/2.json
Insurance 42547 62948281.0 andhra-pradesh 2024 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2024/3.json
Insurance 48014 73915199.0 andhra-pradesh 2024 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/andhra-pradesh/2024/4.json
Insurance 61425 80028914.0 andhra-pradesh 2024 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2020/2.json
Insurance 65 14329.0 arunachal-pradesh 2020 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2020/3.json
Insurance 135 39687.0 arunachal-pradesh 2020 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2020/4.json
Insurance 125 84247.0 arunachal-pradesh 2020 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2021/1.json
Insurance 194 131611.0 arunachal-pradesh 2021 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2021/2.json
Insurance 204 224928.0 arunachal-pradesh 2021 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2021/3.json
Insurance 212 371051.0 arunachal-pradesh 2021 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2021/4.json
Insurance 320 598459.0 arunachal-pradesh 2021 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2022/1.json
Insurance 355 894107.0 arunachal-pradesh 2022 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2022/2.json
Insurance 564 1360231.0 arunachal-pradesh 2022 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2022/3.json
Insurance 510 1300304.0 arunachal-pradesh 2022 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2022/4.json
Insurance 613 1464572.0 arunachal-pradesh 2022 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2023/1.json
Insurance 606 1747475.0 arunachal-pradesh 2023 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2023/2.json
Insurance 696 2095988.0 arunachal-pradesh 2023 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2023/3.json
Insurance 718 1904786.0 arunachal-pradesh 2023 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2023/4.json
Insurance 809 2105408.0 arunachal-pradesh 2023 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2024/1.json
Insurance 1100 2419700.0 arunachal-pradesh 2024 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2024/2.json
Insurance 1147 2353015.0 arunachal-pradesh 2024 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2024/3.json
Insurance 842 1951385.0 arunachal-pradesh 2024 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/arunachal-pradesh/2024/4.json
Insurance 999 2359472.0 arunachal-pradesh 2024 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2020/2.json
Insurance 978 210034.0 assam 2020 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2020/3.json
Insurance 2206 599450.0 assam 2020 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2020/4.json
Insurance 2413 1806801.0 assam 2020 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2021/1.json
Insurance 3167 2334419.0 assam 2021 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2021/2.json
Insurance 3265 3008122.0 assam 2021 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2021/3.json
Insurance 4495 6010865.0 assam 2021 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2021/4.json
Insurance 8622 13962068.0 assam 2021 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2022/1.json
Insurance 16230 27447766.0 assam 2022 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2022/2.json
Insurance 9228 15357811.0 assam 2022 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2022/3.json
Insurance 14149 22543564.0 assam 2022 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2022/4.json
Insurance 18826 29239168.0 assam 2022 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2023/1.json
Insurance 22100 36963888.0 assam 2023 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2023/2.json
Insurance 16475 28368139.0 assam 2023 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2023/3.json
Insurance 22593 35618158.0 assam 2023 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2023/4.json
Insurance 23168 38731734.0 assam 2023 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2024/1.json
Insurance 33097 48107248.0 assam 2024 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2024/2.json
Insurance 22368 34796603.0 assam 2024 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2024/3.json
Insurance 17633 31388971.0 assam 2024 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/assam/2024/4.json
Insurance 21805 35336229.0 assam 2024 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2020/2.json
Insurance 2816 595621.0 bihar 2020 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2020/3.json
Insurance 9733 2161102.0 bihar 2020 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2020/4.json
Insurance 9913 7860932.0 bihar 2020 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2021/1.json
Insurance 12554 8796619.0 bihar 2021 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2021/2.json
Insurance 14301 13301581.0 bihar 2021 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2021/3.json
Insurance 18030 18234941.0 bihar 2021 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2021/4.json
Insurance 22456 27313813.0 bihar 2021 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2022/1.json
Insurance 20253 27755736.0 bihar 2022 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2022/2.json
Insurance 21892 28212833.0 bihar 2022 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2022/3.json
Insurance 28511 34704251.0 bihar 2022 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2022/4.json
Insurance 33895 43914519.0 bihar 2022 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2023/1.json
Insurance 26929 38746711.0 bihar 2023 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2023/2.json
Insurance 29212 40354886.0 bihar 2023 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2023/3.json
Insurance 36550 45832355.0 bihar 2023 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2023/4.json
Insurance 41447 57624322.0 bihar 2023 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2024/1.json
Insurance 51592 63844442.0 bihar 2024 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2024/2.json
Insurance 49101 65285065.0 bihar 2024 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2024/3.json
Insurance 44745 62777286.0 bihar 2024 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/bihar/2024/4.json
Insurance 62662 83739800.0 bihar 2024 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2020/2.json
Insurance 149 29537.0 chandigarh 2020 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2020/3.json
Insurance 264 70969.0 chandigarh 2020 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2020/4.json
Insurance 200 153341.0 chandigarh 2020 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2021/1.json
Insurance 338 238576.0 chandigarh 2021 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2021/2.json
Insurance 378 310943.0 chandigarh 2021 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2021/3.json
Insurance 494 469634.0 chandigarh 2021 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2021/4.json
Insurance 710 835813.0 chandigarh 2021 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2022/1.json
Insurance 792 1150932.0 chandigarh 2022 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2022/2.json
Insurance 1330 1874959.0 chandigarh 2022 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2022/3.json
Insurance 1533 1998439.0 chandigarh 2022 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2022/4.json
Insurance 1403 2024528.0 chandigarh 2022 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2023/1.json
Insurance 1520 2415574.0 chandigarh 2023 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2023/2.json
Insurance 1704 2501107.0 chandigarh 2023 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2023/3.json
Insurance 1883 2660630.0 chandigarh 2023 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2023/4.json
Insurance 1767 3053934.0 chandigarh 2023 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2024/1.json
Insurance 1730 3143984.0 chandigarh 2024 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\insurance\country\india\state/chandigarh/2024/2.json
Insurance 1798 3177315.0 chandigarh 2024 2.json

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar Islands,2020,2,Insurance,6,1360.0
1,Andaman & Nicobar Islands,2020,3,Insurance,41,15380.0
2,Andaman & Nicobar Islands,2020,4,Insurance,124,157975.0
3,Andaman & Nicobar Islands,2021,1,Insurance,225,244266.0
4,Andaman & Nicobar Islands,2021,2,Insurance,137,181504.0
...,...,...,...,...,...,...
677,West Bengal,2023,4,Insurance,72712,100365562.0
678,West Bengal,2024,1,Insurance,79576,104987909.0
679,West Bengal,2024,2,Insurance,67048,89476633.0
680,West Bengal,2024,3,Insurance,77158,107451766.0
681,West Bengal,2024,4,Insurance,91719,120602777.0

In [5]:
# Path to the aggregated transaction data
Agg_trans_state_path=r"C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state"
Agg_trans_state_list=os.listdir(Agg_trans_state_path)

agg_trans_data={'State':[],'Year':[],'Quarter':[],'Transaction_type':[],'Transaction_count':[],'Transaction_amount':[]}

#using for loop to extract the path
for state in Agg_trans_state_list:
  years=os.listdir(f"{Agg_trans_state_path}/{state}")
  for year in years:
    quarter=os.listdir(f"{Agg_trans_state_path}/{state}/{year}")
    for qtr in quarter:
      # Check if the entry is a json file
      if qtr.endswith('.json'):
        path=f"{Agg_trans_state_path}/{state}/{year}/{qtr}"
        print(f"Processing file: {path}")

        #loding json file
        try:
          with open(path,'r') as f:
             data=json.load(f)
          #print(data)

          #extracting data
          for i in data['data']['transactionData']:
             payment_type=i['name']
             count=i['paymentInstruments'][0]['count']
             amount=i['paymentInstruments'][0]['amount']
             print(payment_type,count,amount,state,year,qtr)

             agg_trans_data['State'].append(state)
             agg_trans_data['Year'].append(year)
             agg_trans_data['Quarter'].append(int(qtr.strip('.json')))
             agg_trans_data['Transaction_type'].append(payment_type)
             agg_trans_data['Transaction_count'].append(count)
             agg_trans_data['Transaction_amount'].append(amount)

        except KeyError:
            print(f"Skipping file due to missing keys: {path}")
        except FileNotFoundError:
            print(f"Skipping file not found: {path}")
        except Exception as e:
            print(f"An error occurred while processing {path}: {e}")

#creating dataframe
agg_trans_df=pd.DataFrame(agg_trans_data)
agg_trans_df          

# Formatting the 'State' column for consistency
agg_trans_df ["State"]=agg_trans_df["State"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar Islands')
agg_trans_df["State"]=agg_trans_df["State"].str.replace("-"," ")
agg_trans_df["State"]=agg_trans_df["State"].str.title()
agg_trans_df["State"]=agg_trans_df["State"].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')

agg_trans_df

Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2018/1.json
Recharge & bill payments 4200 1845307.4673655091 andaman-&-nicobar-islands 2018 1.json
Peer-to-peer payments 1871 12138655.299749982 andaman-&-nicobar-islands 2018 1.json
Merchant payments 298 452507.168646613 andaman-&-nicobar-islands 2018 1.json
Financial Services 33 10601.419933464953 andaman-&-nicobar-islands 2018 1.json
Others 256 184689.8662902223 andaman-&-nicobar-islands 2018 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2018/2.json
Recharge & bill payments 6735 2320944.731074479 andaman-&-nicobar-islands 2018 2.json
Peer-to-peer payments 3575 24511925.231047668 andaman-&-nicobar-islands 2018 2.json
Merchant payments 603 1024491.0133579008 andaman-&-nicobar-islands 2018 2.json
Financial Services 59 121336.0270987509 andaman-&-nicobar-islands 2018 2.json
Others 368 359838.50537474576 andaman-&-nicobar-islands 2018 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2018/3.json
Recharge & bill payments 8636 4343504.868377829 andaman-&-nicobar-islands 2018 3.json
Peer-to-peer payments 6448 49270781.541635044 andaman-&-nicobar-islands 2018 3.json
Merchant payments 945 1627359.8394868043 andaman-&-nicobar-islands 2018 3.json
Financial Services 42 1481.4907042806485 andaman-&-nicobar-islands 2018 3.json
Others 194 314343.39410715323 andaman-&-nicobar-islands 2018 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2018/4.json
Recharge & bill payments 11517 5450549.512294375 andaman-&-nicobar-islands 2018 4.json
Peer-to-peer payments 10451 81001456.97825177 andaman-&-nicobar-islands 2018 4.json
Merchant payments 1421 3552027.735492656 andaman-&-nicobar-islands 2018 4.json
Financial Services 29 76035.7877393286 andaman-&-nicobar-islands 2018 4.json
Others 340 468266.0606770435 andaman-&-nicobar-islands 2018 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2019/1.json
Recharge & bill payments 15263 6611459.8729725825 andaman-&-nicobar-islands 2019 1.json
Peer-to-peer payments 13119 91808345.86839552 andaman-&-nicobar-islands 2019 1.json
Merchant payments 1759 3266589.8469614363 andaman-&-nicobar-islands 2019 1.json
Financial Services 62 116250.43671861099 andaman-&-nicobar-islands 2019 1.json
Others 283 497094.6484417205 andaman-&-nicobar-islands 2019 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2019/2.json
Recharge & bill payments 14676 7242448.256212333 andaman-&-nicobar-islands 2019 2.json
Peer-to-peer payments 14481 107525358.66652842 andaman-&-nicobar-islands 2019 2.json
Merchant payments 4031 4702152.616619372 andaman-&-nicobar-islands 2019 2.json
Financial Services 124 113278.91371326067 andaman-&-nicobar-islands 2019 2.json
Others 377 671471.222589792 andaman-&-nicobar-islands 2019 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2019/3.json
Recharge & bill payments 16219 8171737.705916681 andaman-&-nicobar-islands 2019 3.json
Peer-to-peer payments 13767 101079821.10344616 andaman-&-nicobar-islands 2019 3.json
Merchant payments 3519 4428734.574846684 andaman-&-nicobar-islands 2019 3.json
Financial Services 50 158857.94315586874 andaman-&-nicobar-islands 2019 3.json
Others 215 232624.75992853564 andaman-&-nicobar-islands 2019 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2019/4.json
Peer-to-peer payments 18128 121493224.30754511 andaman-&-nicobar-islands 2019 4.json
Recharge & bill payments 13851 9538690.916424634 andaman-&-nicobar-islands 2019 4.json
Merchant payments 2920 5247500.487902376 andaman-&-nicobar-islands 2019 4.json
Financial Services 60 295937.2110898865 andaman-&-nicobar-islands 2019 4.json
Others 200 263177.5944158883 andaman-&-nicobar-islands 2019 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2020/1.json
Peer-to-peer payments 18324 142332401.79234773 andaman-&-nicobar-islands 2020 1.json
Recharge & bill payments 18268 10850414.023977457 andaman-&-nicobar-islands 2020 1.json
Merchant payments 4424 7752871.558217709 andaman-&-nicobar-islands 2020 1.json
Financial Services 66 208231.73071652642 andaman-&-nicobar-islands 2020 1.json
Others 216 332393.19201521645 andaman-&-nicobar-islands 2020 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2020/2.json
Recharge & bill payments 38125 17659622.73418829 andaman-&-nicobar-islands 2020 2.json
Peer-to-peer payments 20303 141728757.73517442 andaman-&-nicobar-islands 2020 2.json
Merchant payments 4004 9236375.740471343 andaman-&-nicobar-islands 2020 2.json
Financial Services 175 706932.1397115812 andaman-&-nicobar-islands 2020 2.json
Others 355 313313.0646014327 andaman-&-nicobar-islands 2020 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2020/3.json
Recharge & bill payments 59310 24756220.875469353 andaman-&-nicobar-islands 2020 3.json
Peer-to-peer payments 40697 289078946.7312394 andaman-&-nicobar-islands 2020 3.json
Merchant payments 16096 22682992.238478824 andaman-&-nicobar-islands 2020 3.json
Financial Services 572 961836.7129860274 andaman-&-nicobar-islands 2020 3.json
Others 808 539449.7721868362 andaman-&-nicobar-islands 2020 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2020/4.json
Peer-to-peer payments 81439 533316526.1814983 andaman-&-nicobar-islands 2020 4.json
Recharge & bill payments 80811 33710030.534383245 andaman-&-nicobar-islands 2020 4.json
Merchant payments 59391 56867468.940003954 andaman-&-nicobar-islands 2020 4.json
Financial Services 965 1880546.9672370641 andaman-&-nicobar-islands 2020 4.json
Others 1925 1508083.6917299272 andaman-&-nicobar-islands 2020 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2021/1.json
Peer-to-peer payments 105458 665391395.715478 andaman-&-nicobar-islands 2021 1.json
Recharge & bill payments 84119 37160922.86506996 andaman-&-nicobar-islands 2021 1.json
Merchant payments 53090 78606979.05751458 andaman-&-nicobar-islands 2021 1.json
Financial Services 884 1469351.0852598653 andaman-&-nicobar-islands 2021 1.json
Others 1201 1077918.666433228 andaman-&-nicobar-islands 2021 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2021/2.json
Peer-to-peer payments 132772 748382044.7707307 andaman-&-nicobar-islands 2021 2.json
Recharge & bill payments 120911 43691961.26275121 andaman-&-nicobar-islands 2021 2.json
Merchant payments 85143 103707408.50908463 andaman-&-nicobar-islands 2021 2.json
Financial Services 960 2038521.5136710338 andaman-&-nicobar-islands 2021 2.json
Others 1628 1327080.0560584562 andaman-&-nicobar-islands 2021 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2021/3.json
Peer-to-peer payments 192321 1077787837.1562996 andaman-&-nicobar-islands 2021 3.json
Recharge & bill payments 136010 51243450.85925055 andaman-&-nicobar-islands 2021 3.json
Merchant payments 118340 176991328.21761328 andaman-&-nicobar-islands 2021 3.json
Financial Services 990 2351013.441729573 andaman-&-nicobar-islands 2021 3.json
Others 2103 1650766.1267105162 andaman-&-nicobar-islands 2021 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2021/4.json
Peer-to-peer payments 285778 1544932663.2744582 andaman-&-nicobar-islands 2021 4.json
Merchant payments 210164 322842314.62433755 andaman-&-nicobar-islands 2021 4.json
Recharge & bill payments 135608 59243518.11464358 andaman-&-nicobar-islands 2021 4.json
Financial Services 1718 3137965.167474068 andaman-&-nicobar-islands 2021 4.json
Others 2855 2453640.142743944 andaman-&-nicobar-islands 2021 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2022/1.json
Peer-to-peer payments 342649 1682328505.7254477 andaman-&-nicobar-islands 2022 1.json
Merchant payments 284298 370091558.68373305 andaman-&-nicobar-islands 2022 1.json
Recharge & bill payments 163401 71300133.66101266 andaman-&-nicobar-islands 2022 1.json
Financial Services 1757 2869682.0229511866 andaman-&-nicobar-islands 2022 1.json
Others 2643 2440321.9820225406 andaman-&-nicobar-islands 2022 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2022/2.json
Merchant payments 449540 510838980.9061847 andaman-&-nicobar-islands 2022 2.json
Peer-to-peer payments 437606 2088309073.4552848 andaman-&-nicobar-islands 2022 2.json
Recharge & bill payments 179515 82232936.61795366 andaman-&-nicobar-islands 2022 2.json
Financial Services 1448 2089862.3927160464 andaman-&-nicobar-islands 2022 2.json
Others 3108 2449496.7081265687 andaman-&-nicobar-islands 2022 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2022/3.json
Merchant payments 716105 693438186.296541 andaman-&-nicobar-islands 2022 3.json
Peer-to-peer payments 622217 2514535154.56483 andaman-&-nicobar-islands 2022 3.json
Recharge & bill payments 240766 97748065.62714244 andaman-&-nicobar-islands 2022 3.json
Financial Services 1814 2166304.9779766416 andaman-&-nicobar-islands 2022 3.json
Others 3477 2744060.670897343 andaman-&-nicobar-islands 2022 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2022/4.json
Merchant payments 956536 906365300.6585041 andaman-&-nicobar-islands 2022 4.json
Peer-to-peer payments 768758 2961630584.8271313 andaman-&-nicobar-islands 2022 4.json
Recharge & bill payments 256050 110037119.66941178 andaman-&-nicobar-islands 2022 4.json
Financial Services 2499 3533987.2301130476 andaman-&-nicobar-islands 2022 4.json
Others 3692 3107412.043626394 andaman-&-nicobar-islands 2022 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2023/1.json
Merchant payments 1122063 1008821751.0 andaman-&-nicobar-islands 2023 1.json
Peer-to-peer payments 862347 3299762230.0 andaman-&-nicobar-islands 2023 1.json
Recharge & bill payments 286024 146338470.0 andaman-&-nicobar-islands 2023 1.json
Financial Services 2515 3556954.0 andaman-&-nicobar-islands 2023 1.json
Others 3443 3049182.0 andaman-&-nicobar-islands 2023 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2023/2.json
Merchant payments 1410653 1159905474.0 andaman-&-nicobar-islands 2023 2.json
Peer-to-peer payments 970525 3664415887.0 andaman-&-nicobar-islands 2023 2.json
Recharge & bill payments 320922 158455723.0 andaman-&-nicobar-islands 2023 2.json
Financial Services 2158 4161814.0 andaman-&-nicobar-islands 2023 2.json
Others 3517 3405338.0 andaman-&-nicobar-islands 2023 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2023/3.json
Merchant payments 1657848 1289780198.0 andaman-&-nicobar-islands 2023 3.json
Peer-to-peer payments 1111211 3757627272.0 andaman-&-nicobar-islands 2023 3.json
Recharge & bill payments 323935 157992380.0 andaman-&-nicobar-islands 2023 3.json
Financial Services 2199 3850023.0 andaman-&-nicobar-islands 2023 3.json
Others 3183 2346918.0 andaman-&-nicobar-islands 2023 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2023/4.json
Merchant payments 2039888 1653303276.0 andaman-&-nicobar-islands 2023 4.json
Peer-to-peer payments 1321796 4420459049.0 andaman-&-nicobar-islands 2023 4.json
Recharge & bill payments 327460 185028400.0 andaman-&-nicobar-islands 2023 4.json
Financial Services 3276 7836466.0 andaman-&-nicobar-islands 2023 4.json
Others 3363 2925308.0 andaman-&-nicobar-islands 2023 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2024/1.json
Merchant payments 2401038 1887811915.0 andaman-&-nicobar-islands 2024 1.json
Peer-to-peer payments 1436380 4771886847.0 andaman-&-nicobar-islands 2024 1.json
Recharge & bill payments 341224 188939343.0 andaman-&-nicobar-islands 2024 1.json
Financial Services 3761 7962745.0 andaman-&-nicobar-islands 2024 1.json
Others 2517 2550985.0 andaman-&-nicobar-islands 2024 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2024/2.json
Merchant payments 2769052 2053269052.0 andaman-&-nicobar-islands 2024 2.json
Peer-to-peer payments 1513157 5033712226.0 andaman-&-nicobar-islands 2024 2.json
Recharge & bill payments 365214 196987648.0 andaman-&-nicobar-islands 2024 2.json
Financial Services 3371 9550750.0 andaman-&-nicobar-islands 2024 2.json
Others 2430 2260654.0 andaman-&-nicobar-islands 2024 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2024/3.json
Merchant payments 3158032 2132361939.0 andaman-&-nicobar-islands 2024 3.json
Peer-to-peer payments 1733054 5305660809.0 andaman-&-nicobar-islands 2024 3.json
Recharge & bill payments 382130 213105223.0 andaman-&-nicobar-islands 2024 3.json
Financial Services 4169 10756400.0 andaman-&-nicobar-islands 2024 3.json
Others 1865 1960638.0 andaman-&-nicobar-islands 2024 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andaman-&-nicobar-islands/2024/4.json
Merchant payments 3666060 2546601178.0 andaman-&-nicobar-islands 2024 4.json
Peer-to-peer payments 1993301 6142805445.0 andaman-&-nicobar-islands 2024 4.json
Recharge & bill payments 389318 214912264.0 andaman-&-nicobar-islands 2024 4.json
Financial Services 12889 12789955.0 andaman-&-nicobar-islands 2024 4.json
Others 2332 3835931.0 andaman-&-nicobar-islands 2024 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andhra-pradesh/2018/1.json
Recharge & bill payments 5027448 892293975.6698562 andhra-pradesh 2018 1.json
Peer-to-peer payments 3049646 10524250283.178782 andhra-pradesh 2018 1.json
Merchant payments 362672 247297640.24000686 andhra-pradesh 2018 1.json
Financial Services 204305 44808449.7639544 andhra-pradesh 2018 1.json
Others 395514 287626042.970705 andhra-pradesh 2018 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andhra-pradesh/2018/2.json
Recharge & bill payments 6456387 1598591488.4880352 andhra-pradesh 2018 2.json
Peer-to-peer payments 4745000 20451493098.8953 andhra-pradesh 2018 2.json
Merchant payments 604847 436785223.86032957 andhra-pradesh 2018 2.json
Financial Services 225621 68952114.81374599 andhra-pradesh 2018 2.json
Others 322063 328092346.575651 andhra-pradesh 2018 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andhra-pradesh/2018/3.json
Peer-to-peer payments 16129591 32738630444.668724 andhra-pradesh 2018 3.json
Recharge & bill payments 7542005 1949098146.8941927 andhra-pradesh 2018 3.json
Merchant payments 1225416 685277254.5076212 andhra-pradesh 2018 3.json
Financial Services 380324 60790077.57437308 andhra-pradesh 2018 3.json
Others 348725 284248675.5700202 andhra-pradesh 2018 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andhra-pradesh/2018/4.json
Peer-to-peer payments 17580086 47011639726.13608 andhra-pradesh 2018 4.json
Recharge & bill payments 9767083 2418164314.470957 andhra-pradesh 2018 4.json
Merchant payments 2622131 1671585888.568256 andhra-pradesh 2018 4.json
Financial Services 400837 57178116.40322068 andhra-pradesh 2018 4.json
Others 389411 315211361.26249415 andhra-pradesh 2018 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andhra-pradesh/2019/1.json
Peer-to-peer payments 37420988 77524329742.2595 andhra-pradesh 2019 1.json
Recharge & bill payments 14022264 3480641602.3771377 andhra-pradesh 2019 1.json
Merchant payments 5043682 2423536770.3706346 andhra-pradesh 2019 1.json
Financial Services 416325 47150177.52982048 andhra-pradesh 2019 1.json
Others 361263 284937624.5393019 andhra-pradesh 2019 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andhra-pradesh/2019/2.json
Peer-to-peer payments 32494402 103924649232.47021 andhra-pradesh 2019 2.json
Recharge & bill payments 14093964 4708345387.9101095 andhra-pradesh 2019 2.json
Merchant payments 9226537 4613405202.681959 andhra-pradesh 2019 2.json
Financial Services 145310 26626696.771042537 andhra-pradesh 2019 2.json
Others 448802 361492238.3966455 andhra-pradesh 2019 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andhra-pradesh/2019/3.json
Peer-to-peer payments 39023491 124338645329.51532 andhra-pradesh 2019 3.json
Recharge & bill payments 20147629 6893984676.598906 andhra-pradesh 2019 3.json
Merchant payments 16581787 7887394038.066369 andhra-pradesh 2019 3.json
Financial Services 122270 29778183.027080443 andhra-pradesh 2019 3.json
Others 413437 298142027.58625776 andhra-pradesh 2019 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andhra-pradesh/2019/4.json
Peer-to-peer payments 57181511 178893550050.68753 andhra-pradesh 2019 4.json
Merchant payments 25122370 13476303367.50486 andhra-pradesh 2019 4.json
Recharge & bill payments 24469888 8335168605.691999 andhra-pradesh 2019 4.json
Financial Services 105662 26796571.745749153 andhra-pradesh 2019 4.json
Others 338672 216496893.16102877 andhra-pradesh 2019 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andhra-pradesh/2020/1.json
Peer-to-peer payments 65452143 223088554055.04755 andhra-pradesh 2020 1.json
Merchant payments 31408022 18603161784.496994 andhra-pradesh 2020 1.json
Recharge & bill payments 30449644 10813530777.973532 andhra-pradesh 2020 1.json
Financial Services 75238 43739133.169823855 andhra-pradesh 2020 1.json
Others 292310 188228538.37489766 andhra-pradesh 2020 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andhra-pradesh/2020/2.json
Peer-to-peer payments 73609921 262731724130.7907 andhra-pradesh 2020 2.json
Recharge & bill payments 41013987 16991006436.573467 andhra-pradesh 2020 2.json
Merchant payments 29976765 22625596525.44269 andhra-pradesh 2020 2.json
Financial Services 140941 145274999.15679634 andhra-pradesh 2020 2.json
Others 176241 90087654.60009979 andhra-pradesh 2020 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\aggregated\transaction\country\india\state/andhra-pradesh/2020/3.json
Peer-to-peer payments 106791894 406461788252.32056 andhra-pradesh 2020 3.json

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar Islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,Andaman & Nicobar Islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,Andaman & Nicobar Islands,2018,1,Merchant payments,298,4.525072e+05
3,Andaman & Nicobar Islands,2018,1,Financial Services,33,1.060142e+04
4,Andaman & Nicobar Islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,West Bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,West Bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,West Bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,West Bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,West Bengal,2024,4,Others,421806,5.053641e+08

In [6]:
# Path to the aggregated user data
Agg_user_state_path=r"C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state"
Agg_user_state_list=os.listdir(Agg_user_state_path)

agg_user_data={'State':[],'Year':[],'Quarter':[],'Device_Brand':[],'Transaction_count':[],'Percentage':[]}

#using for loop to extract the path
for state in Agg_user_state_list:
  years=os.listdir(f"{Agg_user_state_path}/{state}")
  for year in years:
    quarter=os.listdir(f"{Agg_user_state_path}/{state}/{year}")
    for qtr in quarter:
      # Check if the entry is a json file
      if qtr.endswith('.json'):
        path=f"{Agg_user_state_path}/{state}/{year}/{qtr}"
        print(f"Processing file: {path}")

        #loding json file
        try:
          with open(path,'r') as f:
             data=json.load(f)
          #print(data)

          #extracting data
          for i in data['data']['usersByDevice']:
             brand=i['brand']
             count=i['count']
             percentage=i['percentage']
             print(brand,count,percentage,state,year,qtr)

             agg_user_data['State'].append(state)
             agg_user_data['Year'].append(year)
             agg_user_data['Quarter'].append(int(qtr.strip('.json')))
             agg_user_data['Device_Brand'].append(brand)
             agg_user_data['Transaction_count'].append(count)
             agg_user_data['Percentage'].append(percentage)

        except KeyError:
            print(f"Skipping file due to missing keys: {path}")
        except FileNotFoundError:
            print(f"Skipping file not found: {path}")
        except Exception as e:
            print(f"An error occurred while processing {path}: {e}")

#creating dataframe
agg_user_df=pd.DataFrame(agg_user_data)
agg_user_df       

# Formatting the 'State' column for consistency
agg_user_df ["State"]=agg_user_df["State"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar Islands')
agg_user_df["State"]=agg_user_df["State"].str.replace("-"," ")
agg_user_df["State"]=agg_user_df["State"].str.title()
agg_user_df["State"]=agg_user_df["State"].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')

agg_user_df

Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2018/1.json
Xiaomi 1665 0.2470326409495549 andaman-&-nicobar-islands 2018 1.json
Samsung 1445 0.21439169139465875 andaman-&-nicobar-islands 2018 1.json
Vivo 982 0.1456973293768546 andaman-&-nicobar-islands 2018 1.json
Oppo 501 0.07433234421364986 andaman-&-nicobar-islands 2018 1.json
OnePlus 332 0.04925816023738872 andaman-&-nicobar-islands 2018 1.json
Realme 316 0.04688427299703264 andaman-&-nicobar-islands 2018 1.json
Apple 229 0.03397626112759644 andaman-&-nicobar-islands 2018 1.json
Motorola 226 0.03353115727002967 andaman-&-nicobar-islands 2018 1.json
Lenovo 202 0.02997032640949555 andaman-&-nicobar-islands 2018 1.json
Huawei 158 0.02344213649851632 andaman-&-nicobar-islands 2018 1.json
Others 684 0.10148367952522255 andaman-&-nicobar-islands 2018 1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2018/2.json
Xiaomi 2303 0.24486975013290802 andaman-&-nicobar-islands 2018 2.json
Samsung 1923 0.20446570972886763 andaman-&-nicobar-islands 2018 2.json
Vivo 1523 0.1619351408825093 andaman-&-nicobar-islands 2018 2.json
Oppo 708 0.07527910685805422 andaman-&-nicobar-islands 2018 2.json
OnePlus 466 0.049548112706007445 andaman-&-nicobar-islands 2018 2.json
Realme 465 0.049441786283891544 andaman-&-nicobar-islands 2018 2.json
Motorola 319 0.03391812865497076 andaman-&-nicobar-islands 2018 2.json
Apple 308 0.03274853801169591 andaman-&-nicobar-islands 2018 2.json
Lenovo 244 0.025943646996278574 andaman-&-nicobar-islands 2018 2.json
Huawei 230 0.024455077086656035 andaman-&-nicobar-islands 2018 2.json
Others 916 0.09739500265816055 andaman-&-nicobar-islands 2018 2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2018/3.json
Xiaomi 2950 0.24281833895793892 andaman-&-nicobar-islands 2018 3.json
Samsung 2409 0.19828792493209318 andaman-&-nicobar-islands 2018 3.json
Vivo 2063 0.1698082146678739 andaman-&-nicobar-islands 2018 3.json
Oppo 988 0.08132356572557412 andaman-&-nicobar-islands 2018 3.json
OnePlus 617 0.05078607292781299 andaman-&-nicobar-islands 2018 3.json
Realme 603 0.04963371470902955 andaman-&-nicobar-islands 2018 3.json
Motorola 390 0.03210140752325294 andaman-&-nicobar-islands 2018 3.json
Apple 371 0.03053749279776113 andaman-&-nicobar-islands 2018 3.json
Huawei 314 0.0258457486212857 andaman-&-nicobar-islands 2018 3.json
Lenovo 299 0.024611079101160588 andaman-&-nicobar-islands 2018 3.json
Others 1145 0.09424644003621697 andaman-&-nicobar-islands 2018 3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2018/4.json
Xiaomi 3719 0.24431743529102615 andaman-&-nicobar-islands 2018 4.json
Samsung 2936 0.19287872815661541 andaman-&-nicobar-islands 2018 4.json
Vivo 2742 0.1801340165549862 andaman-&-nicobar-islands 2018 4.json
Oppo 1268 0.08330048613848377 andaman-&-nicobar-islands 2018 4.json
Realme 760 0.04992773617133097 andaman-&-nicobar-islands 2018 4.json
OnePlus 721 0.0473656549730653 andaman-&-nicobar-islands 2018 4.json
Motorola 474 0.031139140717382736 andaman-&-nicobar-islands 2018 4.json
Apple 455 0.02989094731309946 andaman-&-nicobar-islands 2018 4.json
Huawei 398 0.02614636710024964 andaman-&-nicobar-islands 2018 4.json
Lenovo 377 0.024766784916568124 andaman-&-nicobar-islands 2018 4.json
Others 1372 0.09013270266719223 andaman-&-nicobar-islands 2018 4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2019/1.json
Xiaomi 4576 0.24607442460744247 andaman-&-nicobar-islands 2019 1.json
Samsung 3567 0.19181544418154442 andaman-&-nicobar-islands 2019 1.json
Vivo 3420 0.18391051839105185 andaman-&-nicobar-islands 2019 1.json
Oppo 1600 0.08604000860400086 andaman-&-nicobar-islands 2019 1.json
Realme 897 0.04823617982361798 andaman-&-nicobar-islands 2019 1.json
OnePlus 855 0.04597762959776296 andaman-&-nicobar-islands 2019 1.json
Motorola 561 0.0301677780167778 andaman-&-nicobar-islands 2019 1.json
Apple 515 0.027694127769412775 andaman-&-nicobar-islands 2019 1.json
Huawei 515 0.027694127769412775 andaman-&-nicobar-islands 2019 1.json
Lenovo 426 0.02290815229081523 andaman-&-nicobar-islands 2019 1.json
Others 1664 0.0894816089481609 andaman-&-nicobar-islands 2019 1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2019/2.json
Xiaomi 5296 0.24370714647278083 andaman-&-nicobar-islands 2019 2.json
Samsung 4165 0.19166168146886936 andaman-&-nicobar-islands 2019 2.json
Vivo 4102 0.18876259721135705 andaman-&-nicobar-islands 2019 2.json
Oppo 1905 0.08766278588191984 andaman-&-nicobar-islands 2019 2.json
Realme 1012 0.04656941696194377 andaman-&-nicobar-islands 2019 2.json
OnePlus 950 0.04371634991486816 andaman-&-nicobar-islands 2019 2.json
Huawei 644 0.029635083521236942 andaman-&-nicobar-islands 2019 2.json
Motorola 630 0.028990842575123098 andaman-&-nicobar-islands 2019 2.json
Apple 569 0.026183792738484195 andaman-&-nicobar-islands 2019 2.json
Lenovo 477 0.021950209378307488 andaman-&-nicobar-islands 2019 2.json
Others 1981 0.09116009387510929 andaman-&-nicobar-islands 2019 2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2019/3.json
Xiaomi 5819 0.24315741088964105 andaman-&-nicobar-islands 2019 3.json
Vivo 4685 0.19577117546278885 andaman-&-nicobar-islands 2019 3.json
Samsung 4508 0.1883749112030421 andaman-&-nicobar-islands 2019 3.json
Oppo 2108 0.08808658225732313 andaman-&-nicobar-islands 2019 3.json
Realme 1158 0.04838911871630939 andaman-&-nicobar-islands 2019 3.json
OnePlus 1045 0.04366720989511512 andaman-&-nicobar-islands 2019 3.json
Huawei 725 0.030295432702352597 andaman-&-nicobar-islands 2019 3.json
Motorola 660 0.02757929046007271 andaman-&-nicobar-islands 2019 3.json
Apple 630 0.026325686348251224 andaman-&-nicobar-islands 2019 3.json
Lenovo 483 0.020183026200325936 andaman-&-nicobar-islands 2019 3.json
Others 2110 0.0881701558647779 andaman-&-nicobar-islands 2019 3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2019/4.json
Xiaomi 6259 0.24110169491525424 andaman-&-nicobar-islands 2019 4.json
Vivo 5190 0.19992295839753466 andaman-&-nicobar-islands 2019 4.json
Samsung 4900 0.18875192604006163 andaman-&-nicobar-islands 2019 4.json
Oppo 2329 0.08971494607087828 andaman-&-nicobar-islands 2019 4.json
Realme 1329 0.051194144838212635 andaman-&-nicobar-islands 2019 4.json
OnePlus 1124 0.04329738058551618 andaman-&-nicobar-islands 2019 4.json
Huawei 798 0.03073959938366718 andaman-&-nicobar-islands 2019 4.json
Motorola 682 0.026271186440677965 andaman-&-nicobar-islands 2019 4.json
Apple 678 0.026117103235747303 andaman-&-nicobar-islands 2019 4.json
Lenovo 488 0.018798151001540832 andaman-&-nicobar-islands 2019 4.json
Others 2183 0.08409090909090909 andaman-&-nicobar-islands 2019 4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2020/1.json
Xiaomi 6803 0.23981246474901297 andaman-&-nicobar-islands 2020 1.json
Vivo 5880 0.20727580372250423 andaman-&-nicobar-islands 2020 1.json
Samsung 5335 0.1880640157924422 andaman-&-nicobar-islands 2020 1.json
Oppo 2557 0.09013677382966723 andaman-&-nicobar-islands 2020 1.json
Realme 1511 0.05326424139875917 andaman-&-nicobar-islands 2020 1.json
OnePlus 1184 0.04173716864072194 andaman-&-nicobar-islands 2020 1.json
Huawei 891 0.03140862944162436 andaman-&-nicobar-islands 2020 1.json
Apple 735 0.02590947546531303 andaman-&-nicobar-islands 2020 1.json
Motorola 715 0.025204455724760294 andaman-&-nicobar-islands 2020 1.json
Lenovo 500 0.017625493513818386 andaman-&-nicobar-islands 2020 1.json
Others 2257 0.0795614777213762 andaman-&-nicobar-islands 2020 1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2020/2.json
Xiaomi 7805 0.2386120452461021 andaman-&-nicobar-islands 2020 2.json
Vivo 7122 0.21773158055640476 andaman-&-nicobar-islands 2020 2.json
Samsung 6030 0.1843472944053806 andaman-&-nicobar-islands 2020 2.json
Oppo 2976 0.09098135126872516 andaman-&-nicobar-islands 2020 2.json
Realme 1761 0.053836747172118615 andaman-&-nicobar-islands 2020 2.json
OnePlus 1271 0.03885661877101804 andaman-&-nicobar-islands 2020 2.json
Huawei 1005 0.030724549067563438 andaman-&-nicobar-islands 2020 2.json
Apple 792 0.024212778966676857 andaman-&-nicobar-islands 2020 2.json
Motorola 779 0.023815346988688476 andaman-&-nicobar-islands 2020 2.json
Lenovo 552 0.01687557321919902 andaman-&-nicobar-islands 2020 2.json
Others 2617 0.0800061143381229 andaman-&-nicobar-islands 2020 2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2020/3.json
Xiaomi 9794 0.2369420587879521 andaman-&-nicobar-islands 2020 3.json
Vivo 9556 0.23118422644248215 andaman-&-nicobar-islands 2020 3.json
Samsung 7572 0.18318616184831257 andaman-&-nicobar-islands 2020 3.json
Oppo 3730 0.09023829684286924 andaman-&-nicobar-islands 2020 3.json
Realme 2285 0.05528002903108745 andaman-&-nicobar-islands 2020 3.json
OnePlus 1440 0.03483730494738115 andaman-&-nicobar-islands 2020 3.json
Huawei 1213 0.029345590903592598 andaman-&-nicobar-islands 2020 3.json
Motorola 907 0.021942663602274103 andaman-&-nicobar-islands 2020 3.json
Apple 870 0.021047538405709446 andaman-&-nicobar-islands 2020 3.json
Lenovo 606 0.014660699165356235 andaman-&-nicobar-islands 2020 3.json
Others 3362 0.08133543002298295 andaman-&-nicobar-islands 2020 3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2020/4.json
Xiaomi 12398 0.23662111611573403 andaman-&-nicobar-islands 2020 4.json
Vivo 12275 0.23427360867241775 andaman-&-nicobar-islands 2020 4.json
Samsung 9938 0.18967096724940835 andaman-&-nicobar-islands 2020 4.json
Oppo 4723 0.0901404687380716 andaman-&-nicobar-islands 2020 4.json
Realme 2996 0.05717993739980151 andaman-&-nicobar-islands 2020 4.json
OnePlus 1638 0.031261928391480266 andaman-&-nicobar-islands 2020 4.json
Huawei 1472 0.028093747614321703 andaman-&-nicobar-islands 2020 4.json
Motorola 1032 0.019696160012214674 andaman-&-nicobar-islands 2020 4.json
Apple 973 0.018570119856477593 andaman-&-nicobar-islands 2020 4.json
Lenovo 708 0.01351248186884495 andaman-&-nicobar-islands 2020 4.json
Others 4243 0.08097946408122758 andaman-&-nicobar-islands 2020 4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2021/1.json
Vivo 13812 0.23913570414488036 andaman-&-nicobar-islands 2021 1.json
Xiaomi 13714 0.2374389694934035 andaman-&-nicobar-islands 2021 1.json
Samsung 10861 0.18804321479275599 andaman-&-nicobar-islands 2021 1.json
Oppo 5158 0.08930364624813879 andaman-&-nicobar-islands 2021 1.json
Realme 3419 0.05919526299387098 andaman-&-nicobar-islands 2021 1.json
OnePlus 1773 0.030697046296616917 andaman-&-nicobar-islands 2021 1.json
Huawei 1575 0.027268949755877972 andaman-&-nicobar-islands 2021 1.json
Motorola 1062 0.018387063263963433 andaman-&-nicobar-islands 2021 1.json
Apple 1056 0.018283181550607708 andaman-&-nicobar-islands 2021 1.json
Tecno 796 0.013781640638526264 andaman-&-nicobar-islands 2021 1.json
Others 4532 0.07846532082135808 andaman-&-nicobar-islands 2021 1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2021/2.json
Vivo 15056 0.2424671873741847 andaman-&-nicobar-islands 2021 2.json
Xiaomi 14788 0.2381512199049843 andaman-&-nicobar-islands 2021 2.json
Samsung 11476 0.18481359207665674 andaman-&-nicobar-islands 2021 2.json
Oppo 5456 0.0878653675819309 andaman-&-nicobar-islands 2021 2.json
Realme 4034 0.06496497302520332 andaman-&-nicobar-islands 2021 2.json
OnePlus 1981 0.031902729688380704 andaman-&-nicobar-islands 2021 2.json
Huawei 1559 0.025106691360012885 andaman-&-nicobar-islands 2021 2.json
Apple 1153 0.018568322731298815 andaman-&-nicobar-islands 2021 2.json
Motorola 1054 0.0169739914646912 andaman-&-nicobar-islands 2021 2.json
Tecno 974 0.015685642966422417 andaman-&-nicobar-islands 2021 2.json
Others 4564 0.073500281826234 andaman-&-nicobar-islands 2021 2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2021/3.json
Vivo 16411 0.24500612104744557 andaman-&-nicobar-islands 2021 3.json
Xiaomi 15938 0.2379445224090054 andaman-&-nicobar-islands 2021 3.json
Samsung 12028 0.17957063091576841 andaman-&-nicobar-islands 2021 3.json
Oppo 5853 0.0873816846316921 andaman-&-nicobar-islands 2021 3.json
Realme 4808 0.0717804783374638 andaman-&-nicobar-islands 2021 3.json
OnePlus 2306 0.03442715953539757 andaman-&-nicobar-islands 2021 3.json
Huawei 1567 0.023394344749335643 andaman-&-nicobar-islands 2021 3.json
Apple 1283 0.01915439968946881 andaman-&-nicobar-islands 2021 3.json
Tecno 1178 0.017586814368039175 andaman-&-nicobar-islands 2021 3.json
Motorola 1017 0.015183183541847063 andaman-&-nicobar-islands 2021 3.json
Others 4593 0.06857066077453644 andaman-&-nicobar-islands 2021 3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2021/4.json
Vivo 17597 0.24515185288381164 andaman-&-nicobar-islands 2021 4.json
Xiaomi 16968 0.2363889662858735 andaman-&-nicobar-islands 2021 4.json
Samsung 12574 0.17517414321538033 andaman-&-nicobar-islands 2021 4.json
Oppo 6127 0.08535803845082196 andaman-&-nicobar-islands 2021 4.json
Realme 5830 0.08122039565338535 andaman-&-nicobar-islands 2021 4.json
OnePlus 2691 0.03748955140707718 andaman-&-nicobar-islands 2021 4.json
Apple 1490 0.020757871273335192 andaman-&-nicobar-islands 2021 4.json
Huawei 1459 0.020325996099191977 andaman-&-nicobar-islands 2021 4.json
Tecno 1417 0.01974087489551407 andaman-&-nicobar-islands 2021 4.json
Motorola 1055 0.014697687378099749 andaman-&-nicobar-islands 2021 4.json
Others 4572 0.06369462245750905 andaman-&-nicobar-islands 2021 4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2022/1.json
Vivo 18688 0.24496644295302014 andaman-&-nicobar-islands 2022 1.json
Xiaomi 17957 0.23538433305369127 andaman-&-nicobar-islands 2022 1.json
Samsung 12955 0.16981700922818793 andaman-&-nicobar-islands 2022 1.json
Realme 6769 0.08872955117449664 andaman-&-nicobar-islands 2022 1.json
Oppo 6461 0.08469221895973154 andaman-&-nicobar-islands 2022 1.json
OnePlus 3005 0.039390205536912755 andaman-&-nicobar-islands 2022 1.json
Tecno 1770 0.02320155201342282 andaman-&-nicobar-islands 2022 1.json
Apple 1634 0.02141883389261745 andaman-&-nicobar-islands 2022 1.json
Huawei 1441 0.018888947147651006 andaman-&-nicobar-islands 2022 1.json
Motorola 1050 0.01376363255033557 andaman-&-nicobar-islands 2022 1.json
Others 4558 0.05974727348993288 andaman-&-nicobar-islands 2022 1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2022/2.json
An error occurred while processing C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2022/2.json: 'NoneType' object is not iterable
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2022/3.json
An error occurred while processing C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2022/3.json: 'NoneType' object is not iterable
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2022/4.json
An error occurred while processing C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2022/4.json: 'NoneType' object is not iterable
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2023/1.json
An error occurred while processing C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2023/1.json: 'NoneType' object is not iterable
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2023/2.json
An error occurred while processing C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2023/2.json: 'NoneType' object is not iterable
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2023/3.json
An error occurred while processing C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2023/3.json: 'NoneType' object is not iterable
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2023/4.json
An error occurred while processing C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2023/4.json: 'NoneType' object is not iterable
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2024/1.json
An error occurred while processing C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2024/1.json: 'NoneType' object is not iterable
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2024/2.json
An error occurred while processing C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2024/2.json: 'NoneType' object is not iterable
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2024/3.json
An error occurred while processing C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2024/3.json: 'NoneType' object is not iterable
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2024/4.json
An error occurred while processing C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andaman-&-nicobar-islands/2024/4.json: 'NoneType' object is not iterable
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\aggregated\user\country\india\state/andhra-pradesh/2018/1.json
Xiaomi 836581 0.25073985823255257 andhra-pradesh 2018 1.json
Samsung 683687 0.20491450493788307 andhra-pradesh 2018 1.json
Vivo 425959 0.1276683301113459 andhra-pradesh 2018 1.json
Oppo 304487 0.09126077117894768 andhra-pradesh 2018 1.json
Realme 236646 0.07092748280357865 andhra-pradesh 2018 1.json

,State,Year,Quarter,Device_Brand,Transaction_count,Percentage
0,Andaman & Nicobar Islands,2018,1,Xiaomi,1665,0.247033
1,Andaman & Nicobar Islands,2018,1,Samsung,1445,0.214392
2,Andaman & Nicobar Islands,2018,1,Vivo,982,0.145697
3,Andaman & Nicobar Islands,2018,1,Oppo,501,0.074332
4,Andaman & Nicobar Islands,2018,1,OnePlus,332,0.049258
...,...,...,...,...,...,...
6727,West Bengal,2022,1,Lenovo,330017,0.015056
6728,West Bengal,2022,1,Infinix,284678,0.012987
6729,West Bengal,2022,1,Asus,280347,0.012790
6730,West Bengal,2022,1,Apple,277752,0.012671
6731,West Bengal,2022,1,Others,2196334,0.100199

In [7]:
# Path to the map insurance data
map_ins_state_path=r"C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state"
map_ins_state_list=os.listdir(map_ins_state_path)

map_ins_data={'State':[],'Year':[],'Quarter':[],'District':[],'Transaction_count':[],'Transaction_amount':[]}

#using for loop to extract the path
for state in map_ins_state_list:
  years=os.listdir(f"{map_ins_state_path}/{state}")
  for year in years:
    quarter=os.listdir(f"{map_ins_state_path}/{state}/{year}")
    for qtr in quarter:
      # Check if the entry is a json file
      if qtr.endswith('.json'):
        path=f"{map_ins_state_path}/{state}/{year}/{qtr}"
        print(f"Processing file: {path}")

        #loding json file
        try:
          with open(path,'r') as f:
             data=json.load(f)
          #print(data)

          #extracting data
          for i in data['data']['hoverDataList']:
             district=i['name']
             count=i['metric'][0]['count']
             amount=i['metric'][0]['amount']
             print(district,count,amount,state,year,qtr)

             map_ins_data['State'].append(state)
             map_ins_data['Year'].append(year)
             map_ins_data['Quarter'].append(int(qtr.strip('.json')))
             map_ins_data['District'].append(district)
             map_ins_data['Transaction_count'].append(count)
             map_ins_data['Transaction_amount'].append(amount)

        except KeyError:
            print(f"Skipping file due to missing keys: {path}")
        except FileNotFoundError:
            print(f"Skipping file not found: {path}")
        except Exception as e:
            print(f"An error occurred while processing {path}: {e}")

#creating dataframe
map_ins_df=pd.DataFrame(map_ins_data)
map_ins_df   

# Formatting the 'State' column for consistency
map_ins_df ["State"]=map_ins_df ["State"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar Islands')
map_ins_df ["State"]=map_ins_df ["State"].str.replace("-"," ")
map_ins_df ["State"]=map_ins_df ["State"].str.title()
map_ins_df ["State"]=map_ins_df ["State"].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')

map_ins_df

Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2020/2.json
south andaman district 3 795.0 andaman-&-nicobar-islands 2020 2.json
nicobars district 3 565.0 andaman-&-nicobar-islands 2020 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2020/3.json
north and middle andaman district 1 281.0 andaman-&-nicobar-islands 2020 3.json
south andaman district 35 13651.0 andaman-&-nicobar-islands 2020 3.json
nicobars district 5 1448.0 andaman-&-nicobar-islands 2020 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2020/4.json
north and middle andaman district 13 17734.0 andaman-&-nicobar-islands 2020 4.json
south andaman district 109 137494.0 andaman-&-nicobar-islands 2020 4.json
nicobars district 2 2747.0 andaman-&-nicobar-islands 2020 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2021/1.json
north and middle andaman district 48 63978.0 andaman-&-nicobar-islands 2021 1.json
south andaman district 164 167044.0 andaman-&-nicobar-islands 2021 1.json
nicobars district 13 13244.0 andaman-&-nicobar-islands 2021 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2021/2.json
north and middle andaman district 28 45311.0 andaman-&-nicobar-islands 2021 2.json
south andaman district 105 121104.0 andaman-&-nicobar-islands 2021 2.json
nicobars district 4 15089.0 andaman-&-nicobar-islands 2021 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2021/3.json
north and middle andaman district 33 50997.0 andaman-&-nicobar-islands 2021 3.json
south andaman district 182 223699.0 andaman-&-nicobar-islands 2021 3.json
nicobars district 15 30539.0 andaman-&-nicobar-islands 2021 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2021/4.json
north and middle andaman district 81 182061.0 andaman-&-nicobar-islands 2021 4.json
south andaman district 632 800758.0 andaman-&-nicobar-islands 2021 4.json
nicobars district 44 73561.0 andaman-&-nicobar-islands 2021 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2022/1.json
north and middle andaman district 48 85229.0 andaman-&-nicobar-islands 2022 1.json
south andaman district 692 982206.0 andaman-&-nicobar-islands 2022 1.json
nicobars district 28 63852.0 andaman-&-nicobar-islands 2022 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2022/2.json
north and middle andaman district 45 90403.0 andaman-&-nicobar-islands 2022 2.json
south andaman district 430 633029.0 andaman-&-nicobar-islands 2022 2.json
nicobars district 26 56308.0 andaman-&-nicobar-islands 2022 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2022/3.json
north and middle andaman district 70 129013.0 andaman-&-nicobar-islands 2022 3.json
south andaman district 535 687813.0 andaman-&-nicobar-islands 2022 3.json
nicobars district 38 85640.0 andaman-&-nicobar-islands 2022 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2022/4.json
north and middle andaman district 112 224198.0 andaman-&-nicobar-islands 2022 4.json
south andaman district 750 1114857.0 andaman-&-nicobar-islands 2022 4.json
nicobars district 39 102155.0 andaman-&-nicobar-islands 2022 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2023/1.json
north and middle andaman district 85 178969.0 andaman-&-nicobar-islands 2023 1.json
south andaman district 872 1172083.0 andaman-&-nicobar-islands 2023 1.json
nicobars district 47 88146.0 andaman-&-nicobar-islands 2023 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2023/2.json
north and middle andaman district 56 109742.0 andaman-&-nicobar-islands 2023 2.json
south andaman district 670 1060976.0 andaman-&-nicobar-islands 2023 2.json
nicobars district 42 62677.0 andaman-&-nicobar-islands 2023 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2023/3.json
north and middle andaman district 77 133536.0 andaman-&-nicobar-islands 2023 3.json
south andaman district 682 1052324.0 andaman-&-nicobar-islands 2023 3.json
nicobars district 36 65285.0 andaman-&-nicobar-islands 2023 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2023/4.json
north and middle andaman district 95 156995.0 andaman-&-nicobar-islands 2023 4.json
south andaman district 1006 1504528.0 andaman-&-nicobar-islands 2023 4.json
nicobars district 44 96298.0 andaman-&-nicobar-islands 2023 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2024/1.json
north and middle andaman district 125 229226.0 andaman-&-nicobar-islands 2024 1.json
south andaman district 1190 1657627.0 andaman-&-nicobar-islands 2024 1.json
nicobars district 56 77703.0 andaman-&-nicobar-islands 2024 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2024/2.json
north and middle andaman district 74 164686.0 andaman-&-nicobar-islands 2024 2.json
south andaman district 974 1513489.0 andaman-&-nicobar-islands 2024 2.json
nicobars district 49 66519.0 andaman-&-nicobar-islands 2024 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2024/3.json
north and middle andaman district 95 151791.0 andaman-&-nicobar-islands 2024 3.json
south andaman district 1044 1530179.0 andaman-&-nicobar-islands 2024 3.json
nicobar district 51 68638.0 andaman-&-nicobar-islands 2024 3.json
nicobars district 1 2192.0 andaman-&-nicobar-islands 2024 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andaman-&-nicobar-islands/2024/4.json
north and middle andaman district 131 219770.0 andaman-&-nicobar-islands 2024 4.json
south andaman district 1085 1670015.0 andaman-&-nicobar-islands 2024 4.json
nicobar district 77 136595.0 andaman-&-nicobar-islands 2024 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2020/2.json
east godavari district 1913 352220.0 andhra-pradesh 2020 2.json
srikakulam district 536 107046.0 andhra-pradesh 2020 2.json
spsr nellore district 931 176423.0 andhra-pradesh 2020 2.json
vizianagaram district 893 166029.0 andhra-pradesh 2020 2.json
visakhapatnam district 3504 614212.0 andhra-pradesh 2020 2.json
prakasam district 847 161709.0 andhra-pradesh 2020 2.json
anantapur district 2739 485777.0 andhra-pradesh 2020 2.json
ysr district 1978 343002.0 andhra-pradesh 2020 2.json
west godavari district 1074 202289.0 andhra-pradesh 2020 2.json
kurnool district 825 158720.0 andhra-pradesh 2020 2.json
chittoor district 2228 395099.0 andhra-pradesh 2020 2.json
guntur district 1938 344326.0 andhra-pradesh 2020 2.json
krishna district 2698 475539.0 andhra-pradesh 2020 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2020/3.json
east godavari district 3783 970549.0 andhra-pradesh 2020 3.json
srikakulam district 1535 383049.0 andhra-pradesh 2020 3.json
spsr nellore district 5509 1259159.0 andhra-pradesh 2020 3.json
vizianagaram district 2999 691281.0 andhra-pradesh 2020 3.json
visakhapatnam district 7906 1892376.0 andhra-pradesh 2020 3.json
prakasam district 2565 722751.0 andhra-pradesh 2020 3.json
anantapur district 2911 764850.0 andhra-pradesh 2020 3.json
ysr district 3397 847519.0 andhra-pradesh 2020 3.json
west godavari district 2543 696749.0 andhra-pradesh 2020 3.json
kurnool district 3493 841970.0 andhra-pradesh 2020 3.json
chittoor district 4422 1178762.0 andhra-pradesh 2020 3.json
guntur district 4230 1083584.0 andhra-pradesh 2020 3.json
krishna district 4519 1093882.0 andhra-pradesh 2020 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2020/4.json
east godavari district 1965 1355741.0 andhra-pradesh 2020 4.json
srikakulam district 811 546440.0 andhra-pradesh 2020 4.json
spsr nellore district 1348 810758.0 andhra-pradesh 2020 4.json
vizianagaram district 897 651040.0 andhra-pradesh 2020 4.json
visakhapatnam district 3464 2203761.0 andhra-pradesh 2020 4.json
prakasam district 1190 572976.0 andhra-pradesh 2020 4.json
anantapur district 1534 794053.0 andhra-pradesh 2020 4.json
ysr district 1165 631876.0 andhra-pradesh 2020 4.json
west godavari district 1390 906282.0 andhra-pradesh 2020 4.json
kurnool district 1092 500768.0 andhra-pradesh 2020 4.json
chittoor district 1727 1168506.0 andhra-pradesh 2020 4.json
guntur district 2570 1620649.0 andhra-pradesh 2020 4.json
krishna district 2311 1222782.0 andhra-pradesh 2020 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2021/1.json
east godavari district 1937 1065604.0 andhra-pradesh 2021 1.json
srikakulam district 854 588769.0 andhra-pradesh 2021 1.json
spsr nellore district 1323 714947.0 andhra-pradesh 2021 1.json
vizianagaram district 781 526804.0 andhra-pradesh 2021 1.json
visakhapatnam district 4006 2403199.0 andhra-pradesh 2021 1.json
prakasam district 1182 585354.0 andhra-pradesh 2021 1.json
anantapur district 1264 621128.0 andhra-pradesh 2021 1.json
ysr district 1265 729565.0 andhra-pradesh 2021 1.json
west godavari district 1460 850251.0 andhra-pradesh 2021 1.json
kurnool district 1270 508161.0 andhra-pradesh 2021 1.json
chittoor district 1629 1058050.0 andhra-pradesh 2021 1.json
guntur district 2412 1398326.0 andhra-pradesh 2021 1.json
krishna district 2722 1699716.0 andhra-pradesh 2021 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2021/2.json
east godavari district 2343 1695121.0 andhra-pradesh 2021 2.json
srikakulam district 842 755796.0 andhra-pradesh 2021 2.json
spsr nellore district 1817 1245872.0 andhra-pradesh 2021 2.json
vizianagaram district 815 702006.0 andhra-pradesh 2021 2.json
visakhapatnam district 4655 3497573.0 andhra-pradesh 2021 2.json
prakasam district 5308 2719134.0 andhra-pradesh 2021 2.json
anantapur district 1631 1284850.0 andhra-pradesh 2021 2.json
ysr district 1404 1026195.0 andhra-pradesh 2021 2.json
west godavari district 4170 2327122.0 andhra-pradesh 2021 2.json
kurnool district 1410 941389.0 andhra-pradesh 2021 2.json
chittoor district 2392 1839579.0 andhra-pradesh 2021 2.json
guntur district 2967 2201793.0 andhra-pradesh 2021 2.json
krishna district 3451 2494257.0 andhra-pradesh 2021 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2021/3.json
east godavari district 2248 2073825.0 andhra-pradesh 2021 3.json
srikakulam district 798 803258.0 andhra-pradesh 2021 3.json
spsr nellore district 1486 1161025.0 andhra-pradesh 2021 3.json
vizianagaram district 736 628946.0 andhra-pradesh 2021 3.json
visakhapatnam district 4044 3191769.0 andhra-pradesh 2021 3.json
prakasam district 1050 877683.0 andhra-pradesh 2021 3.json
anantapur district 1329 1311735.0 andhra-pradesh 2021 3.json
ysr district 1137 1033282.0 andhra-pradesh 2021 3.json
west godavari district 1452 1216098.0 andhra-pradesh 2021 3.json
kurnool district 1027 796678.0 andhra-pradesh 2021 3.json
chittoor district 1991 1995617.0 andhra-pradesh 2021 3.json
guntur district 2519 2102143.0 andhra-pradesh 2021 3.json
krishna district 3258 2722279.0 andhra-pradesh 2021 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2021/4.json
east godavari district 2532 3543718.0 andhra-pradesh 2021 4.json
srikakulam district 1116 1152210.0 andhra-pradesh 2021 4.json
spsr nellore district 2369 2345876.0 andhra-pradesh 2021 4.json
vizianagaram district 924 916336.0 andhra-pradesh 2021 4.json
visakhapatnam district 4176 5425896.0 andhra-pradesh 2021 4.json
prakasam district 1181 1328774.0 andhra-pradesh 2021 4.json
anantapur district 1322 2101400.0 andhra-pradesh 2021 4.json
ysr district 1449 1479933.0 andhra-pradesh 2021 4.json
west godavari district 1262 1853561.0 andhra-pradesh 2021 4.json
kurnool district 910 1306288.0 andhra-pradesh 2021 4.json
chittoor district 2444 3100521.0 andhra-pradesh 2021 4.json
guntur district 2709 3214794.0 andhra-pradesh 2021 4.json
krishna district 3029 3841028.0 andhra-pradesh 2021 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2022/1.json
east godavari district 3605 5199664.0 andhra-pradesh 2022 1.json
srikakulam district 1004 1393633.0 andhra-pradesh 2022 1.json
spsr nellore district 1878 2608475.0 andhra-pradesh 2022 1.json
vizianagaram district 949 1344329.0 andhra-pradesh 2022 1.json
visakhapatnam district 5196 6953446.0 andhra-pradesh 2022 1.json
prakasam district 1797 2181402.0 andhra-pradesh 2022 1.json
anantapur district 1551 2556602.0 andhra-pradesh 2022 1.json
ysr district 1439 2086496.0 andhra-pradesh 2022 1.json
west godavari district 1991 3109555.0 andhra-pradesh 2022 1.json
kurnool district 995 1641988.0 andhra-pradesh 2022 1.json
chittoor district 2887 4304499.0 andhra-pradesh 2022 1.json
guntur district 2748 3988284.0 andhra-pradesh 2022 1.json
krishna district 3914 5279784.0 andhra-pradesh 2022 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2022/2.json
east godavari district 3103 3899091.0 andhra-pradesh 2022 2.json
srikakulam district 946 1282760.0 andhra-pradesh 2022 2.json
spsr nellore district 2063 2686947.0 andhra-pradesh 2022 2.json
vizianagaram district 1145 1412957.0 andhra-pradesh 2022 2.json
visakhapatnam district 5851 7046107.0 andhra-pradesh 2022 2.json
prakasam district 1962 2331922.0 andhra-pradesh 2022 2.json
anantapur district 1794 2729962.0 andhra-pradesh 2022 2.json
ysr district 1418 1920103.0 andhra-pradesh 2022 2.json
west godavari district 2141 2903957.0 andhra-pradesh 2022 2.json
kurnool district 1233 1573534.0 andhra-pradesh 2022 2.json
chittoor district 2836 4207850.0 andhra-pradesh 2022 2.json
guntur district 3115 3979873.0 andhra-pradesh 2022 2.json
krishna district 4578 5733009.0 andhra-pradesh 2022 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2022/3.json
east godavari district 4355 5505134.0 andhra-pradesh 2022 3.json
srikakulam district 1079 1444643.0 andhra-pradesh 2022 3.json
spsr nellore district 2593 3257610.0 andhra-pradesh 2022 3.json
vizianagaram district 1270 1573445.0 andhra-pradesh 2022 3.json
visakhapatnam district 6720 7779967.0 andhra-pradesh 2022 3.json
prakasam district 2137 2552054.0 andhra-pradesh 2022 3.json
anantapur district 1934 2719786.0 andhra-pradesh 2022 3.json
ysr district 1892 2559169.0 andhra-pradesh 2022 3.json
west godavari district 2314 3113617.0 andhra-pradesh 2022 3.json
kurnool district 1318 1720753.0 andhra-pradesh 2022 3.json
chittoor district 3729 5145111.0 andhra-pradesh 2022 3.json
guntur district 4431 5271211.0 andhra-pradesh 2022 3.json
krishna district 5529 6149431.0 andhra-pradesh 2022 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2022/4.json
east godavari district 4450 5856052.0 andhra-pradesh 2022 4.json
srikakulam district 1294 1623449.0 andhra-pradesh 2022 4.json
spsr nellore district 2733 3658896.0 andhra-pradesh 2022 4.json
vizianagaram district 1373 1680979.0 andhra-pradesh 2022 4.json
visakhapatnam district 7636 9911879.0 andhra-pradesh 2022 4.json
prakasam district 2400 2848596.0 andhra-pradesh 2022 4.json
anantapur district 2425 3710468.0 andhra-pradesh 2022 4.json
ysr district 2261 2993022.0 andhra-pradesh 2022 4.json
west godavari district 2623 3513389.0 andhra-pradesh 2022 4.json
kurnool district 1810 2859172.0 andhra-pradesh 2022 4.json
chittoor district 4641 6166050.0 andhra-pradesh 2022 4.json
guntur district 5199 6244165.0 andhra-pradesh 2022 4.json
krishna district 5484 6977122.0 andhra-pradesh 2022 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2023/1.json
east godavari district 4069 5915626.0 andhra-pradesh 2023 1.json
srikakulam district 1100 1628429.0 andhra-pradesh 2023 1.json
spsr nellore district 2461 3621734.0 andhra-pradesh 2023 1.json
vizianagaram district 1104 1619607.0 andhra-pradesh 2023 1.json
visakhapatnam district 6752 9502319.0 andhra-pradesh 2023 1.json
prakasam district 1437 2188369.0 andhra-pradesh 2023 1.json
anantapur district 1565 2882540.0 andhra-pradesh 2023 1.json
ysr district 1509 2235497.0 andhra-pradesh 2023 1.json
west godavari district 2196 3370241.0 andhra-pradesh 2023 1.json
kurnool district 1208 2088411.0 andhra-pradesh 2023 1.json
chittoor district 3284 5677174.0 andhra-pradesh 2023 1.json
guntur district 3542 4957590.0 andhra-pradesh 2023 1.json
krishna district 4693 6275818.0 andhra-pradesh 2023 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2023/2.json
east godavari district 3690 5519480.0 andhra-pradesh 2023 2.json
srikakulam district 1083 1556225.0 andhra-pradesh 2023 2.json
spsr nellore district 2468 3679371.0 andhra-pradesh 2023 2.json
vizianagaram district 1227 1530183.0 andhra-pradesh 2023 2.json
visakhapatnam district 7000 8910217.0 andhra-pradesh 2023 2.json
prakasam district 1311 1880405.0 andhra-pradesh 2023 2.json
anantapur district 1688 3027497.0 andhra-pradesh 2023 2.json
ysr district 1652 2426306.0 andhra-pradesh 2023 2.json
west godavari district 2140 3383512.0 andhra-pradesh 2023 2.json
kurnool district 1473 2483871.0 andhra-pradesh 2023 2.json
chittoor district 3756 5988173.0 andhra-pradesh 2023 2.json
guntur district 3725 5015442.0 andhra-pradesh 2023 2.json
krishna district 5163 6666796.0 andhra-pradesh 2023 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2023/3.json
east godavari district 4157 5720660.0 andhra-pradesh 2023 3.json
srikakulam district 1308 1724487.0 andhra-pradesh 2023 3.json
spsr nellore district 3082 3962298.0 andhra-pradesh 2023 3.json
vizianagaram district 1274 1526422.0 andhra-pradesh 2023 3.json
visakhapatnam district 8972 11107138.0 andhra-pradesh 2023 3.json
prakasam district 1695 2170370.0 andhra-pradesh 2023 3.json
anantapur district 1947 3392196.0 andhra-pradesh 2023 3.json
ysr district 1900 2732465.0 andhra-pradesh 2023 3.json
west godavari district 2308 3162591.0 andhra-pradesh 2023 3.json
kurnool district 1723 2310997.0 andhra-pradesh 2023 3.json
chittoor district 3993 6350318.0 andhra-pradesh 2023 3.json
guntur district 4604 5810698.0 andhra-pradesh 2023 3.json
krishna district 6187 7831756.0 andhra-pradesh 2023 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\insurance\hover\country\india\state/andhra-pradesh/2023/4.json
east godavari district 4294 6404501.0 andhra-pradesh 2023 4.json
srikakulam district 1327 1851290.0 andhra-pradesh 2023 4.json

,State,Year,Quarter,District,Transaction_count,Transaction_amount
0,Andaman & Nicobar Islands,2020,2,south andaman district,3,795.0
1,Andaman & Nicobar Islands,2020,2,nicobars district,3,565.0
2,Andaman & Nicobar Islands,2020,3,north and middle andaman district,1,281.0
3,Andaman & Nicobar Islands,2020,3,south andaman district,35,13651.0
4,Andaman & Nicobar Islands,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,West Bengal,2024,4,alipurduar district,1023,1613143.0
13872,West Bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,West Bengal,2024,4,nadia district,3807,5031294.0
13874,West Bengal,2024,4,birbhum district,1818,2423290.0
13875,West Bengal,2024,4,purba medinipur district,3559,4439061.0

In [7]:
# Path to the map transaction data
map_trans_state_path=r"C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state"
map_trans_state_list=os.listdir(map_trans_state_path)

map_trans_data={'State':[],'Year':[],'Quarter':[],'District':[],'Transaction_count':[],'Transaction_amount':[]}

#using for loop to extract the path
for state in map_trans_state_list:
  years=os.listdir(f"{map_trans_state_path}/{state}")
  for year in years:
    quarter=os.listdir(f"{map_trans_state_path}/{state}/{year}")
    for qtr in quarter:
      # Check if the entry is a json file
      if qtr.endswith('.json'):
        path=f"{map_trans_state_path}/{state}/{year}/{qtr}"
        print(f"Processing file: {path}")

        #loding json file
        try:
          with open(path,'r') as f:
             data=json.load(f)
          #print(data)

          #extracting data
          for i in data['data']['hoverDataList']:
             district=i['name']
             count=i['metric'][0]['count']
             amount=i['metric'][0]['amount']
             print(district,count,amount,state,year,qtr)

             map_trans_data['State'].append(state)
             map_trans_data['Year'].append(year)
             map_trans_data['Quarter'].append(int(qtr.strip('.json')))
             map_trans_data['District'].append(district)
             map_trans_data['Transaction_count'].append(count)
             map_trans_data['Transaction_amount'].append(amount)

        except KeyError:
            print(f"Skipping file due to missing keys: {path}")
        except FileNotFoundError:
            print(f"Skipping file not found: {path}")
        except Exception as e:
            print(f"An error occurred while processing {path}: {e}")

#creating dataframe
map_trans_df=pd.DataFrame(map_trans_data)
map_trans_df      

# Formatting the 'State' column for consistency
map_trans_df ["State"]=map_trans_df ["State"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar Islands')
map_trans_df ["State"]=map_trans_df ["State"].str.replace("-"," ")
map_trans_df ["State"]=map_trans_df ["State"].str.title()
map_trans_df ["State"]=map_trans_df ["State"].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')

Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2018/1.json
north and middle andaman district 442 931663.0770939873 andaman-&-nicobar-islands 2018 1.json
south andaman district 5688 12560249.34366581 andaman-&-nicobar-islands 2018 1.json
nicobars district 528 1139848.801225994 andaman-&-nicobar-islands 2018 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2018/2.json
north and middle andaman district 825 1317863.0834906558 andaman-&-nicobar-islands 2018 2.json
south andaman district 9395 23948235.51634325 andaman-&-nicobar-islands 2018 2.json
nicobars district 1120 3072436.9081196385 andaman-&-nicobar-islands 2018 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2018/3.json
north and middle andaman district 1283 4901529.518499676 andaman-&-nicobar-islands 2018 3.json
south andaman district 13511 44268112.46425246 andaman-&-nicobar-islands 2018 3.json
nicobars district 1471 6387829.151558982 andaman-&-nicobar-islands 2018 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2018/4.json
north and middle andaman district 2137 7955635.917688001 andaman-&-nicobar-islands 2018 4.json
south andaman district 20136 75411840.8018554 andaman-&-nicobar-islands 2018 4.json
nicobars district 1485 7180859.354911782 andaman-&-nicobar-islands 2018 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2019/1.json
north and middle andaman district 3264 9561708.736298349 andaman-&-nicobar-islands 2019 1.json
south andaman district 25683 85501972.38780196 andaman-&-nicobar-islands 2019 1.json
nicobars district 1539 7236059.549389593 andaman-&-nicobar-islands 2019 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2019/2.json
north and middle andaman district 3371 8612103.137888122 andaman-&-nicobar-islands 2019 2.json
south andaman district 28490 102530955.71341258 andaman-&-nicobar-islands 2019 2.json
nicobars district 1828 9111650.82436246 andaman-&-nicobar-islands 2019 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2019/3.json
north and middle andaman district 4049 11481466.283356793 andaman-&-nicobar-islands 2019 3.json
south andaman district 27421 91023888.32848613 andaman-&-nicobar-islands 2019 3.json
nicobars district 2300 11566421.475451011 andaman-&-nicobar-islands 2019 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2019/4.json
north and middle andaman district 4716 13524056.784573946 andaman-&-nicobar-islands 2019 4.json
south andaman district 27843 110930312.20611623 andaman-&-nicobar-islands 2019 4.json
nicobars district 2600 12384161.52668771 andaman-&-nicobar-islands 2019 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2020/1.json
north and middle andaman district 5674 14697371.617857102 andaman-&-nicobar-islands 2020 1.json
south andaman district 32713 134679396.90582755 andaman-&-nicobar-islands 2020 1.json
nicobars district 2911 12099543.773590054 andaman-&-nicobar-islands 2020 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2020/2.json
north and middle andaman district 10979 22447714.061058953 andaman-&-nicobar-islands 2020 2.json
south andaman district 48088 132855778.74838585 andaman-&-nicobar-islands 2020 2.json
nicobars district 3895 14341508.60470232 andaman-&-nicobar-islands 2020 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2020/3.json
north and middle andaman district 16747 33486883.370425556 andaman-&-nicobar-islands 2020 3.json
south andaman district 95323 282366109.20523936 andaman-&-nicobar-islands 2020 3.json
nicobars district 5413 22166453.754695386 andaman-&-nicobar-islands 2020 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2020/4.json
north and middle andaman district 29349 68941322.38839513 andaman-&-nicobar-islands 2020 4.json
south andaman district 186494 523122462.88302904 andaman-&-nicobar-islands 2020 4.json
nicobars district 8688 35218871.04342849 andaman-&-nicobar-islands 2020 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2021/1.json
north and middle andaman district 27358 75027255.27919498 andaman-&-nicobar-islands 2021 1.json
south andaman district 207092 669604045.1248703 andaman-&-nicobar-islands 2021 1.json
nicobars district 10302 39075266.9856904 andaman-&-nicobar-islands 2021 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2021/2.json
north and middle andaman district 39200 90233388.79463302 andaman-&-nicobar-islands 2021 2.json
south andaman district 286907 760893020.5704944 andaman-&-nicobar-islands 2021 2.json
nicobars district 15307 48020606.74716837 andaman-&-nicobar-islands 2021 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2021/3.json
north and middle andaman district 46592 118254865.82750683 andaman-&-nicobar-islands 2021 3.json
south andaman district 382418 1116789010.6459613 andaman-&-nicobar-islands 2021 3.json
nicobars district 20754 74980519.3281361 andaman-&-nicobar-islands 2021 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2021/4.json
north and middle andaman district 53115 156486112.28732437 andaman-&-nicobar-islands 2021 4.json
south andaman district 558571 1694794708.0093334 andaman-&-nicobar-islands 2021 4.json
nicobars district 24437 81329281.0269996 andaman-&-nicobar-islands 2021 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2022/1.json
north and middle andaman district 60059 161624878.52274162 andaman-&-nicobar-islands 2022 1.json
south andaman district 705512 1872991195.902684 andaman-&-nicobar-islands 2022 1.json
nicobars district 29177 94414127.64974089 andaman-&-nicobar-islands 2022 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2022/2.json
north and middle andaman district 72573 195693167.78757268 andaman-&-nicobar-islands 2022 2.json
south andaman district 954875 2357326563.362071 andaman-&-nicobar-islands 2022 2.json
nicobars district 43769 132900618.93062323 andaman-&-nicobar-islands 2022 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2022/3.json
north and middle andaman district 79574 211581970.34202656 andaman-&-nicobar-islands 2022 3.json
south andaman district 1455255 2967719400.849909 andaman-&-nicobar-islands 2022 3.json
nicobars district 49550 131330400.94545083 andaman-&-nicobar-islands 2022 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2022/4.json
north and middle andaman district 93297 241431284.3558103 andaman-&-nicobar-islands 2022 4.json
south andaman district 1835592 3600887266.099448 andaman-&-nicobar-islands 2022 4.json
nicobars district 58646 142355853.97352526 andaman-&-nicobar-islands 2022 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2023/1.json
north and middle andaman district 152187 392080332.0 andaman-&-nicobar-islands 2023 1.json
south andaman district 2030078 3867385426.0 andaman-&-nicobar-islands 2023 1.json
nicobars district 94127 202062829.0 andaman-&-nicobar-islands 2023 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2023/2.json
north and middle andaman district 181149 462414675.0 andaman-&-nicobar-islands 2023 2.json
south andaman district 2417058 4297737197.0 andaman-&-nicobar-islands 2023 2.json
nicobars district 109568 230192364.0 andaman-&-nicobar-islands 2023 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2023/3.json
north and middle andaman district 198547 495623030.0 andaman-&-nicobar-islands 2023 3.json
south andaman district 2771397 4462201588.0 andaman-&-nicobar-islands 2023 3.json
nicobars district 128432 253772173.0 andaman-&-nicobar-islands 2023 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2023/4.json
north and middle andaman district 230234 540759631.0 andaman-&-nicobar-islands 2023 4.json
south andaman district 3311962 5417264997.0 andaman-&-nicobar-islands 2023 4.json
nicobars district 153587 311527871.0 andaman-&-nicobar-islands 2023 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2024/1.json
north and middle andaman district 266400 601756070.0 andaman-&-nicobar-islands 2024 1.json
south andaman district 3751724 5952049462.0 andaman-&-nicobar-islands 2024 1.json
nicobars district 166796 305346303.0 andaman-&-nicobar-islands 2024 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2024/2.json
north and middle andaman district 313301 676844858.0 andaman-&-nicobar-islands 2024 2.json
south andaman district 4153251 6285248054.0 andaman-&-nicobar-islands 2024 2.json
nicobars district 186672 333687418.0 andaman-&-nicobar-islands 2024 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2024/3.json
north and middle andaman district 364075 724234808.0 andaman-&-nicobar-islands 2024 3.json
south andaman district 4704639 6567147442.0 andaman-&-nicobar-islands 2024 3.json
nicobar district 210536 372462759.0 andaman-&-nicobar-islands 2024 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andaman-&-nicobar-islands/2024/4.json
north and middle andaman district 411230 759100984.0 andaman-&-nicobar-islands 2024 4.json
south andaman district 5419850 7760167334.0 andaman-&-nicobar-islands 2024 4.json
nicobar district 232820 401676455.0 andaman-&-nicobar-islands 2024 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andhra-pradesh/2018/1.json
east godavari district 943935 1235785515.5997267 andhra-pradesh 2018 1.json
srikakulam district 458921 587778028.9183557 andhra-pradesh 2018 1.json
spsr nellore district 531612 676643237.8069417 andhra-pradesh 2018 1.json
vizianagaram district 420990 505783445.78162 andhra-pradesh 2018 1.json
visakhapatnam district 1256469 1749966196.5049946 andhra-pradesh 2018 1.json
prakasam district 534757 748990775.8676485 andhra-pradesh 2018 1.json
anantapur district 638664 788830646.0324218 andhra-pradesh 2018 1.json
ysr district 487333 681481931.0936775 andhra-pradesh 2018 1.json
west godavari district 577090 853547668.7532666 andhra-pradesh 2018 1.json
kurnool district 679623 764905298.7350456 andhra-pradesh 2018 1.json
chittoor district 830324 1009621878.0870512 andhra-pradesh 2018 1.json
guntur district 815932 1108686589.0266829 andhra-pradesh 2018 1.json
krishna district 863935 1284255179.6156201 andhra-pradesh 2018 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andhra-pradesh/2018/2.json
east godavari district 1221677 2168914928.4239016 andhra-pradesh 2018 2.json
srikakulam district 559868 929392017.3670053 andhra-pradesh 2018 2.json
spsr nellore district 780454 1542057934.0108962 andhra-pradesh 2018 2.json
vizianagaram district 529588 811711367.5080048 andhra-pradesh 2018 2.json
visakhapatnam district 1641192 2987853607.2939095 andhra-pradesh 2018 2.json
prakasam district 739991 1571167562.1276276 andhra-pradesh 2018 2.json
anantapur district 937023 1690366079.0557928 andhra-pradesh 2018 2.json
ysr district 690842 1415500367.6861844 andhra-pradesh 2018 2.json
west godavari district 786033 1688025212.3045945 andhra-pradesh 2018 2.json
kurnool district 968439 1531888665.6843233 andhra-pradesh 2018 2.json
chittoor district 1185723 1990419125.8937118 andhra-pradesh 2018 2.json
guntur district 1088101 2108475811.7859967 andhra-pradesh 2018 2.json
krishna district 1224987 2448141593.4919834 andhra-pradesh 2018 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andhra-pradesh/2018/3.json
east godavari district 3226907 3551247095.307447 andhra-pradesh 2018 3.json
srikakulam district 1073883 1318322236.598471 andhra-pradesh 2018 3.json
spsr nellore district 1308890 2215938596.185108 andhra-pradesh 2018 3.json
vizianagaram district 970132 1163546006.895916 andhra-pradesh 2018 3.json
visakhapatnam district 3394576 4821892253.393524 andhra-pradesh 2018 3.json
prakasam district 1319651 2346453445.483843 andhra-pradesh 2018 3.json
anantapur district 1815215 2681787750.464165 andhra-pradesh 2018 3.json
ysr district 1557444 2235904512.2542048 andhra-pradesh 2018 3.json
west godavari district 1431282 2309078492.8058147 andhra-pradesh 2018 3.json
kurnool district 2921189 2908389261.539773 andhra-pradesh 2018 3.json
chittoor district 2297429 3283517630.720593 andhra-pradesh 2018 3.json
guntur district 1912529 3127764663.180438 andhra-pradesh 2018 3.json
krishna district 2396934 3754202654.3844614 andhra-pradesh 2018 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andhra-pradesh/2018/4.json
east godavari district 3052762 4652624623.436675 andhra-pradesh 2018 4.json
srikakulam district 1252807 1870278609.504549 andhra-pradesh 2018 4.json
spsr nellore district 1814997 3293448556.9734454 andhra-pradesh 2018 4.json
vizianagaram district 1386787 1817673252.5417767 andhra-pradesh 2018 4.json
visakhapatnam district 4791421 7366635864.849373 andhra-pradesh 2018 4.json
prakasam district 1692862 3255254226.03728 andhra-pradesh 2018 4.json
anantapur district 2286391 3975878156.329829 andhra-pradesh 2018 4.json
ysr district 1732527 3252340063.2478595 andhra-pradesh 2018 4.json
west godavari district 1688482 3237504255.4632454 andhra-pradesh 2018 4.json
kurnool district 2508530 3626544852.4069242 andhra-pradesh 2018 4.json
chittoor district 3166201 4979093890.223491 andhra-pradesh 2018 4.json
guntur district 2546620 4730251217.696959 andhra-pradesh 2018 4.json
krishna district 2839161 5416251838.130407 andhra-pradesh 2018 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andhra-pradesh/2019/1.json
east godavari district 5440146 7382264724.59952 andhra-pradesh 2019 1.json
srikakulam district 2526855 3407912878.4152584 andhra-pradesh 2019 1.json
spsr nellore district 3333584 5161932216.216368 andhra-pradesh 2019 1.json
vizianagaram district 2798241 3364576948.299301 andhra-pradesh 2019 1.json
visakhapatnam district 9690866 13459857440.552685 andhra-pradesh 2019 1.json
prakasam district 2931081 4807527779.215151 andhra-pradesh 2019 1.json
anantapur district 3891336 6044730653.191345 andhra-pradesh 2019 1.json
ysr district 2852197 4915811593.896078 andhra-pradesh 2019 1.json
west godavari district 2829437 4623764455.47309 andhra-pradesh 2019 1.json
kurnool district 4193432 5541564892.509682 andhra-pradesh 2019 1.json
chittoor district 6486813 8223371732.233585 andhra-pradesh 2019 1.json
guntur district 4846553 7765934169.404485 andhra-pradesh 2019 1.json
krishna district 5443981 9061346433.072681 andhra-pradesh 2019 1.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andhra-pradesh/2019/2.json
east godavari district 4699261 9116404622.47651 andhra-pradesh 2019 2.json
srikakulam district 2019203 4066576539.936839 andhra-pradesh 2019 2.json
spsr nellore district 3141891 6880873007.4820595 andhra-pradesh 2019 2.json
vizianagaram district 2272320 4443041665.039663 andhra-pradesh 2019 2.json
visakhapatnam district 11705738 20797479804.029076 andhra-pradesh 2019 2.json
prakasam district 2670529 6262396448.455349 andhra-pradesh 2019 2.json
anantapur district 3578836 7830782361.377665 andhra-pradesh 2019 2.json
ysr district 2606284 6376856828.130632 andhra-pradesh 2019 2.json
west godavari district 2402074 5676818258.955046 andhra-pradesh 2019 2.json
kurnool district 3895824 7358285187.018034 andhra-pradesh 2019 2.json
chittoor district 5983308 10982727976.224325 andhra-pradesh 2019 2.json
guntur district 5005275 10405246943.481495 andhra-pradesh 2019 2.json
krishna district 6428472 13437029115.620754 andhra-pradesh 2019 2.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andhra-pradesh/2019/3.json
east godavari district 6537303 11387726470.57774 andhra-pradesh 2019 3.json
srikakulam district 2556296 4610131289.524039 andhra-pradesh 2019 3.json
spsr nellore district 4150195 8256600118.735449 andhra-pradesh 2019 3.json
vizianagaram district 2861581 4922069039.19216 andhra-pradesh 2019 3.json
visakhapatnam district 16694947 26944837120.046288 andhra-pradesh 2019 3.json
prakasam district 3430750 7354502261.150911 andhra-pradesh 2019 3.json
anantapur district 4889720 9554081289.488277 andhra-pradesh 2019 3.json
ysr district 3296586 7447544274.2117815 andhra-pradesh 2019 3.json
west godavari district 3179541 6627629029.01413 andhra-pradesh 2019 3.json
kurnool district 5139134 9025632779.412457 andhra-pradesh 2019 3.json
chittoor district 8201783 13837455758.755266 andhra-pradesh 2019 3.json
guntur district 6942304 13075661264.188034 andhra-pradesh 2019 3.json
krishna district 8408474 16404073560.500784 andhra-pradesh 2019 3.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andhra-pradesh/2019/4.json
east godavari district 9285739 16816774065.301317 andhra-pradesh 2019 4.json
srikakulam district 3712555 6832369301.879345 andhra-pradesh 2019 4.json
spsr nellore district 5877804 11786014089.194027 andhra-pradesh 2019 4.json
vizianagaram district 3998234 7175851807.068796 andhra-pradesh 2019 4.json
visakhapatnam district 23594874 39133296330.044624 andhra-pradesh 2019 4.json
prakasam district 4865473 10604077824.801035 andhra-pradesh 2019 4.json
anantapur district 6764112 13887248889.064066 andhra-pradesh 2019 4.json
ysr district 4793157 10865073855.730783 andhra-pradesh 2019 4.json
west godavari district 4596479 9710614747.20177 andhra-pradesh 2019 4.json
kurnool district 7001958 13233105728.54823 andhra-pradesh 2019 4.json
chittoor district 11246986 19298476027.875484 andhra-pradesh 2019 4.json
guntur district 9761330 18565626418.035915 andhra-pradesh 2019 4.json
krishna district 11719402 23039786404.04664 andhra-pradesh 2019 4.json
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\transaction\hover\country\india\state/andhra-pradesh/2020/1.json
east godavari district 11346242 21854701379.428688 andhra-pradesh 2020 1.json
srikakulam district 4835092 9777575594.177538 andhra-pradesh 2020 1.json

In [8]:
# Path to the map user data
map_user_state_path=r"C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state"
map_user_state_list=os.listdir(map_user_state_path)

map_user_data={'State':[],'Year':[],'Quarter':[],'District':[],'RegisteredUsers':[],'AppOpens':[]}

#using for loop to extract the path
for state in map_user_state_list:
  years=os.listdir(f"{map_user_state_path}/{state}")
  for year in years:
    quarter=os.listdir(f"{map_user_state_path}/{state}/{year}")
    for qtr in quarter:
      # Check if the entry is a json file
      if qtr.endswith('.json'):
        path=f"{map_user_state_path}/{state}/{year}/{qtr}"
        print(f"Processing file: {path}")

        #loding json file
        try:
          with open(path,'r') as f:
             data=json.load(f)
          #print(data)

          #extracting data
          for district, hover_data in data['data']['hoverData'].items():
           registeredUsers=hover_data['registeredUsers']
           appOpens=hover_data['appOpens']
           print(district,registeredUsers,appOpens)

           map_user_data['State'].append(state)
           map_user_data['Year'].append(year)
           map_user_data['Quarter'].append(int(qtr.strip('.json')))
           map_user_data['District'].append(district)
           map_user_data['RegisteredUsers'].append(registeredUsers)
           map_user_data['AppOpens'].append(appOpens)

        except KeyError:
            print(f"Skipping file due to missing keys: {path}")
        except FileNotFoundError:
            print(f"Skipping file not found: {path}")
        except Exception as e:
            print(f"An error occurred while processing {path}: {e}")

#creating dataframe
map_user_df=pd.DataFrame(map_user_data)
map_user_df   

# Formatting the 'State' column for consistency
map_user_df ["State"]=map_user_df ["State"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar Islands')
map_user_df ["State"]=map_user_df ["State"].str.replace("-"," ")
map_user_df ["State"]=map_user_df ["State"].str.title()
map_user_df ["State"]=map_user_df ["State"].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')

map_user_df

Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2018/1.json
north and middle andaman district 632 0
south andaman district 5846 0
nicobars district 262 0
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2018/2.json
north and middle andaman district 911 0
south andaman district 8143 0
nicobars district 351 0
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2018/3.json
north and middle andaman district 1208 0
south andaman district 10474 0
nicobars district 467 0
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2018/4.json
north and middle andaman district 1553 0
south andaman district 13133 0
nicobars district 536 0
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2019/1.json
north and middle andaman district 2013 0
south andaman district 15961 0
nicobars district 622 0
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2019/2.json
north and middle andaman district 2417 6118
south andaman district 18621 43569
nicobars district 693 2953
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2019/3.json
north and middle andaman district 2662 22064
south andaman district 20518 138190
nicobars district 751 10853
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2019/4.json
north and middle andaman district 2955 26253
south andaman district 22202 139646
nicobars district 803 11113
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2020/1.json
north and middle andaman district 3315 30444
south andaman district 24174 151529
nicobars district 879 11613
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2020/2.json
north and middle andaman district 4100 56992
south andaman district 27626 231071
nicobars district 984 17009
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2020/3.json
north and middle andaman district 5355 76553
south andaman district 34833 417785
nicobars district 1147 21227
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2020/4.json
north and middle andaman district 7076 125915
south andaman district 43908 725321
nicobars district 1412 35972
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2021/1.json
north and middle andaman district 7833 121680
south andaman district 48352 837589
nicobars district 1573 45067
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2021/2.json
north and middle andaman district 8493 596182
south andaman district 51903 1270226
nicobars district 1699 381815
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2021/3.json
north and middle andaman district 9263 759314
south andaman district 55873 1771107
nicobars district 1846 591204
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2021/4.json
north and middle andaman district 10002 171921
south andaman district 59807 1863037
nicobars district 1971 77952
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2022/1.json
north and middle andaman district 10720 904869
south andaman district 63487 2368756
nicobars district 2081 573782
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2022/2.json
north and middle andaman district 11379 963824
south andaman district 66959 3404740
nicobars district 2192 811449
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2022/3.json
north and middle andaman district 11897 1176567
south andaman district 70445 3607286
nicobars district 2300 1284501
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2022/4.json
north and middle andaman district 12361 313502
south andaman district 73692 3881359
nicobars district 2389 159232
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2023/1.json
north and middle andaman district 12941 3103047
south andaman district 77052 5450795
nicobars district 2491 2458822
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2023/2.json
north and middle andaman district 13600 3174229
south andaman district 80112 6884657
nicobars district 2617 4679790
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2023/3.json
north and middle andaman district 14216 7130284
south andaman district 83305 5950899
nicobars district 2734 7463896
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2023/4.json
north and middle andaman district 14813 1869462
south andaman district 86348 7452861
nicobars district 2817 523637
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2024/1.json
north and middle andaman district 15539 9022450
south andaman district 89907 12147903
nicobars district 2965 7368398
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2024/2.json
north and middle andaman district 16183 6159746
south andaman district 93421 6749599
nicobars district 3083 3967538
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2024/3.json
north and middle andaman district 21728 9789799
south andaman district 143250 6545536
nicobar district 7495 3219511
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andaman-&-nicobar-islands/2024/4.json
north and middle andaman district 22547 2194985
south andaman district 148543 15101583
nicobar district 7698 1395115
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2018/1.json
east godavari district 350356 0
srikakulam district 143839 0
visakhapatnam district 497187 0
prakasam district 189949 0
anantapur district 241192 0
kurnool district 240133 0
guntur district 317065 0
krishna district 323673 0
spsr nellore district 194475 0
vizianagaram district 128905 0
ysr district 186800 0
west godavari district 213335 0
chittoor district 309541 0
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2018/2.json
east godavari district 454398 0
srikakulam district 186913 0
visakhapatnam district 636052 0
prakasam district 253458 0
anantapur district 326383 0
kurnool district 319313 0
guntur district 420326 0
krishna district 431965 0
spsr nellore district 261049 0
vizianagaram district 167327 0
ysr district 248657 0
west godavari district 282393 0
chittoor district 414306 0
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2018/3.json
east godavari district 558982 0
srikakulam district 228456 0
visakhapatnam district 769096 0
prakasam district 314899 0
anantapur district 405855 0
kurnool district 394311 0
guntur district 518931 0
krishna district 537086 0
spsr nellore district 322446 0
vizianagaram district 203655 0
ysr district 308391 0
west godavari district 349782 0
chittoor district 515727 0
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2018/4.json
east godavari district 694455 0
srikakulam district 284874 0
visakhapatnam district 978288 0
prakasam district 394962 0
anantapur district 510892 0
kurnool district 498582 0
guntur district 659552 0
krishna district 682479 0
spsr nellore district 407495 0
vizianagaram district 257824 0
ysr district 387058 0
west godavari district 435668 0
chittoor district 665280 0
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2019/1.json
east godavari district 839277 0
srikakulam district 345775 0
visakhapatnam district 1174517 0
prakasam district 474260 0
anantapur district 612162 0
kurnool district 599422 0
guntur district 802394 0
krishna district 833694 0
spsr nellore district 491908 0
vizianagaram district 313334 0
ysr district 460590 0
west godavari district 523372 0
chittoor district 812314 0
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2019/2.json
east godavari district 945181 7156762
srikakulam district 392764 3230330
visakhapatnam district 1318740 13681907
prakasam district 539462 4488365
anantapur district 695114 6056591
kurnool district 680118 6240480
guntur district 915256 7268875
krishna district 952300 7822632
spsr nellore district 558303 4774473
vizianagaram district 355058 3541678
ysr district 519031 4345848
west godavari district 592185 3853094
chittoor district 925491 8914216
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2019/3.json
east godavari district 1057167 28275322
srikakulam district 437939 11813195
visakhapatnam district 1460464 54836001
prakasam district 598568 16267041
anantapur district 773656 22845084
kurnool district 755024 22827473
guntur district 1026418 28477132
krishna district 1066546 30077671
spsr nellore district 619592 17768733
vizianagaram district 394375 13065845
ysr district 574109 15833900
west godavari district 662102 14227407
chittoor district 1032733 34638738
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2019/4.json
east godavari district 1195228 38299189
srikakulam district 496266 16353822
visakhapatnam district 1620235 70749983
prakasam district 673522 21639748
anantapur district 873033 30278539
kurnool district 846885 29676997
guntur district 1158708 37846179
krishna district 1199971 39407473
spsr nellore district 697154 23608360
vizianagaram district 443810 17515311
ysr district 646642 21543798
west godavari district 750078 19393528
chittoor district 1156351 44888591
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2020/1.json
east godavari district 1329664 46142746
srikakulam district 552007 20975989
visakhapatnam district 1763581 77558624
prakasam district 748655 26870693
anantapur district 971850 36900103
kurnool district 936293 34198350
guntur district 1289678 45282758
krishna district 1331602 46079408
spsr nellore district 775440 28879364
vizianagaram district 490683 21562104
ysr district 717865 26166193
west godavari district 843835 24542868
chittoor district 1270907 51354573
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2020/2.json
east godavari district 1459116 45884498
srikakulam district 608002 23808009
visakhapatnam district 1904719 69684456
prakasam district 830709 32255276
anantapur district 1076953 39704703
kurnool district 1035093 36268390
guntur district 1426271 44267596
krishna district 1459041 41234166
spsr nellore district 854459 30816403
vizianagaram district 537798 24370380
ysr district 796769 29644037
west godavari district 944829 26583613
chittoor district 1385916 49820171
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2020/3.json
east godavari district 1601940 64292857
srikakulam district 667858 31794753
visakhapatnam district 2058346 102589371
prakasam district 915240 44970519
anantapur district 1186851 55714787
kurnool district 1132240 49164718
guntur district 1567595 62427501
krishna district 1599289 61028114
spsr nellore district 937176 43951448
vizianagaram district 587784 31199437
ysr district 877909 41578067
west godavari district 1053674 38126238
chittoor district 1506503 69462572
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2020/4.json
east godavari district 1746280 82605352
srikakulam district 726761 36770992
visakhapatnam district 2209658 124730170
prakasam district 999462 52839846
anantapur district 1295872 69562398
kurnool district 1230466 60615045
guntur district 1712940 81291172
krishna district 1744028 81787771
spsr nellore district 1022944 54765443
vizianagaram district 634462 35110885
ysr district 959182 49596303
west godavari district 1163179 51170162
chittoor district 1631331 88232999
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2021/1.json
east godavari district 1878769 91478749
srikakulam district 782604 40590058
visakhapatnam district 2368081 135908324
prakasam district 1075936 56911479
anantapur district 1394849 73375049
kurnool district 1323411 65326230
guntur district 1843237 92731167
krishna district 1876458 92941553
spsr nellore district 1100541 60691988
vizianagaram district 681621 37752539
ysr district 1032689 53525815
west godavari district 1254117 57392671
chittoor district 1751420 99083825
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2021/2.json
east godavari district 2006272 84705076
srikakulam district 837958 43740255
visakhapatnam district 2526830 114313154
prakasam district 1151232 76850749
anantapur district 1492738 104568606
kurnool district 1415585 81894678
guntur district 1968681 88248064
krishna district 2002662 85771678
spsr nellore district 1176334 74049216
vizianagaram district 729509 42684475
ysr district 1103004 72255265
west godavari district 1339377 65118788
chittoor district 1870723 110505432
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2021/3.json
east godavari district 2150622 103626560
srikakulam district 902008 48622126
visakhapatnam district 2707931 139540800
prakasam district 1239147 91533813
anantapur district 1606735 124985545
kurnool district 1522196 101210508
guntur district 2110878 106621413
krishna district 2145423 104358295
spsr nellore district 1263550 90102349
vizianagaram district 784444 46277311
ysr district 1183377 86369956
west godavari district 1436576 80244808
chittoor district 2007011 135043395
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2021/4.json
east godavari district 2294347 142536856
srikakulam district 965335 61654215
visakhapatnam district 2888774 188757640
prakasam district 1325728 86410317
anantapur district 1719437 120768682
kurnool district 1628242 97379271
guntur district 2252443 130920743
krishna district 2288148 134436469
spsr nellore district 1349290 90814672
vizianagaram district 839606 56101822
ysr district 1262963 83534122
west godavari district 1532898 100007280
chittoor district 2141818 154395512
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2022/1.json
east godavari district 2432305 87134562
srikakulam district 1027283 46691467
visakhapatnam district 3061324 88803090
prakasam district 1408929 104851997
anantapur district 1827094 155792533
kurnool district 1729513 119653214
guntur district 2387051 88844052
krishna district 2423373 85871644
spsr nellore district 1431664 101671767
vizianagaram district 892889 44804002
ysr district 1339782 98878499
west godavari district 1626039 87642475
chittoor district 2270705 144146671
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2022/2.json
east godavari district 2564165 93383888
srikakulam district 1086164 51087942
visakhapatnam district 3226029 93552701
prakasam district 1487589 108172758
anantapur district 1928213 181499094
kurnool district 1825280 136447455
guntur district 2514794 91997209
krishna district 2552107 95341487
spsr nellore district 1509927 108755384
vizianagaram district 943242 50230853
ysr district 1412848 106157470
west godavari district 1714357 103338893
chittoor district 2392549 158771722
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2022/3.json
east godavari district 2702234 85780890
srikakulam district 1147016 46323107
visakhapatnam district 3397514 87888969
prakasam district 1567520 114185009
anantapur district 2030824 181038520
kurnool district 1924127 143715547
guntur district 2647100 91146114
krishna district 2685215 86220959
spsr nellore district 1588875 105928407
vizianagaram district 995141 46767889
ysr district 1487140 107976611
west godavari district 1805967 97509407
chittoor district 2517657 162524274
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2022/4.json
east godavari district 2835087 173720880
srikakulam district 1204785 72666058
visakhapatnam district 3566854 208604256
prakasam district 1642503 94432083
anantapur district 2128066 136685634
kurnool district 2018290 105333688
guntur district 2774365 144773169
krishna district 2813645 156902257
spsr nellore district 1663684 103101986
vizianagaram district 1044490 64406405
ysr district 1556901 93975668
west godavari district 1893310 129116752
chittoor district 2636036 189655966
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2023/1.json
east godavari district 2965296 98931582
srikakulam district 1263204 48743038
visakhapatnam district 3732544 107253885
prakasam district 1719910 112502189
anantapur district 2228505 177793392
kurnool district 2114023 149581663
guntur district 2900895 103514892
krishna district 2941585 98727644
spsr nellore district 1740294 111993275
vizianagaram district 1094782 55519223
ysr district 1628595 109842928
west godavari district 1980446 102965151
chittoor district 2755784 164669558
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2023/2.json
east godavari district 3082893 101375784
srikakulam district 1317771 48040159
visakhapatnam district 3877504 115516314
prakasam district 1792637 104288559
anantapur district 2323796 164437247
kurnool district 2202517 142843895
guntur district 3014655 97915941
krishna district 3054956 99723659
spsr nellore district 1811781 113350865
vizianagaram district 1141578 55405616
ysr district 1694843 98586928
west godavari district 2059880 116005083
chittoor district 2865250 170462384
Processing file: C:\Users\sathishkumar\Downloads\pulse\data\map\user\hover\country\india\state/andhra-pradesh/2023/3.json
east godavari district 3211557 83823834
srikakulam district 1375950 44064462
visakhapatnam district 4035323 116087299
prakasam district 1868997 94303883
anantapur district 2421293 152875757
kurnool district 2295754 124493256
guntur district 3137289 71855007
krishna district 3177643 73280755
spsr nellore district 1887005 73583227
vizianagaram district 1190571 41978556
ysr district 1764648 78787151
west godavari district 2146530 73274852
chittoor district 2981337 129032458

,State,Year,Quarter,District,RegisteredUsers,AppOpens
0,Andaman & Nicobar Islands,2018,1,north and middle andaman district,632,0
1,Andaman & Nicobar Islands,2018,1,south andaman district,5846,0
2,Andaman & Nicobar Islands,2018,1,nicobars district,262,0
3,Andaman & Nicobar Islands,2018,2,north and middle andaman district,911,0
4,Andaman & Nicobar Islands,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,West Bengal,2024,4,alipurduar district,475688,31842355
20604,West Bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,West Bengal,2024,4,nadia district,1861738,98740305
20606,West Bengal,2024,4,birbhum district,1114220,73465525
20607,West Bengal,2024,4,purba medinipur district,1717074,108350777

In [9]:
# Path to the top insurance data
top_ins_state_path=r"C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state"
top_ins_state_list=os.listdir(top_ins_state_path)

top_ins_data={'State':[],'Year':[],'Quarter':[],'Pincodes':[],'Transaction_count':[],'Transaction_amount':[]}

#using for loop to extract the path
for state in top_ins_state_list:
  years=os.listdir(f"{top_ins_state_path}/{state}")
  for year in years:
    quarter=os.listdir(f"{top_ins_state_path}/{state}/{year}")
    for qtr in quarter:
      # Check if the entry is a json file
      if qtr.endswith('.json'):
        path=f"{top_ins_state_path}/{state}/{year}/{qtr}"
        print(f"Processing file: {path}")

        #loding json file
        try:
          with open(path,'r') as f:
             data=json.load(f)
          #print(data)

          #extracting data
          for i in data['data']['pincodes']:
            entityname=i['entityName']
            count=i['metric']['count']
            amount=i['metric']['amount']
           
            top_ins_data['State'].append(state)
            top_ins_data['Year'].append(year)
            top_ins_data['Quarter'].append(int(qtr.strip('.json')))
            top_ins_data['Pincodes'].append(entityname)
            top_ins_data['Transaction_count'].append(count)
            top_ins_data['Transaction_amount'].append(amount)

        except KeyError:
            print(f"Skipping file due to missing keys: {path}")
        except FileNotFoundError:
            print(f"Skipping file not found: {path}")
        except Exception as e:
            print(f"An error occurred while processing {path}: {e}")


#creating dataframe
top_ins_df=pd.DataFrame(top_ins_data)
top_ins_df    

# Formatting the 'State' column for consistency
top_ins_df ["State"]=top_ins_df ["State"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar Islands')
top_ins_df ["State"]=top_ins_df ["State"].str.replace("-"," ")  
top_ins_df ["State"]=top_ins_df ["State"].str.title()
top_ins_df ["State"]=top_ins_df ["State"].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')

top_ins_df

Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andaman-&-nicobar-islands/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/andhra-pradesh/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/arunachal-pradesh/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/assam/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/bihar/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chandigarh/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/chhattisgarh/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2022/4.json

,State,Year,Quarter,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar Islands,2020,2,744301,3,565.0
1,Andaman & Nicobar Islands,2020,2,744104,2,513.0
2,Andaman & Nicobar Islands,2020,2,744101,1,282.0
3,Andaman & Nicobar Islands,2020,3,744112,9,3432.0
4,Andaman & Nicobar Islands,2020,3,744105,7,3948.0
...,...,...,...,...,...,...
6663,West Bengal,2024,4,711101,713,750354.0
6664,West Bengal,2024,4,700091,642,969634.0
6665,West Bengal,2024,4,700150,627,761501.0
6666,West Bengal,2024,4,700039,619,787836.0
6667,West Bengal,2024,4,700156,574,888613.0

In [10]:
# Path to the top transaction data
top_trans_state_path=r"C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state"
top_trans_state_list=os.listdir(top_trans_state_path)

top_trans_data={'State':[],'Year':[],'Quarter':[],'Pincodes':[],'Transaction_count':[],'Transaction_amount':[]}

#using for loop to extract the path
for state in top_trans_state_list:
  years=os.listdir(f"{top_trans_state_path}/{state}")
  for year in years:
    quarter=os.listdir(f"{top_trans_state_path}/{state}/{year}")
    for qtr in quarter:
      # Check if the entry is a json file
      if qtr.endswith('.json'):
        path=f"{top_trans_state_path}/{state}/{year}/{qtr}"
        print(f"Processing file: {path}")

        #loding json file
        try:
          with open(path,'r') as f:
             data=json.load(f)
          #print(data)

          #extracting data
          for i in data['data']['pincodes']:
            entityname=i['entityName']
            count=i['metric']['count']
            amount=i['metric']['amount']
            print(entityname,count,amount)

            top_trans_data['State'].append(state)
            top_trans_data['Year'].append(year)
            top_trans_data['Quarter'].append(int(qtr.strip('.json')))
            top_trans_data['Pincodes'].append(entityname)
            top_trans_data['Transaction_count'].append(count)
            top_trans_data['Transaction_amount'].append(amount)

        except KeyError:
            print(f"Skipping file due to missing keys: {path}")
        except FileNotFoundError:
            print(f"Skipping file not found: {path}")

#creating dataframe
top_trans_df=pd.DataFrame(top_trans_data)
top_trans_df     

#Formatting the 'State' column for consistency
top_trans_df ["State"]=top_trans_df ["State"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar Islands')
top_trans_df ["State"]=top_trans_df ["State"].str.replace("-"," ")  
top_trans_df ["State"]=top_trans_df ["State"].str.title()
top_trans_df ["State"]=top_trans_df ["State"].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')

top_trans_df

Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2018/1.json
744101 1622 2769297.9039997994
744103 1223 2238041.8716124697
744102 969 3519059.937562449
744105 685 1298560.9515503529
744104 340 1039715.3111450541
744107 302 556059.5308556345
744301 283 445739.1633851439
744112 269 333709.56700413954
744202 193 238914.01667155625
744302 168 547469.6509380838
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2018/2.json
744101 2701 6310089.917084678
744103 1965 4752146.698501162
744102 1525 5810267.574788321
744105 997 2200332.971862734
744301 767 1953749.3787199226
744104 659 1650346.1906506256
744107 594 1601569.9821441039
744112 432 578829.1795229593
744202 405 626523.9803147907
744302 291 1026590.0735863491
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2018/3.json
744101 3462 10833893.444488766
744103 3182 10184154.358592123
744102 2224 10365275.479700703
744105 1613 5152534.080403434
744104 1029 2588077.6866583927
744301 975 4256576.349618757
744112 579 1145815.7801705198
744107 547 1492405.302862124
744302 417 1976781.9199490356
744202 341 2099404.0789861116
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2018/4.json
744101 4674 16392855.280625317
744103 4576 17022520.257624768
744102 3306 17019977.183053624
744105 2513 9935282.832151461
744104 1432 6091757.917089159
744211 1225 3451359.606027063
744301 928 4606293.657525641
744112 759 2208675.0435713646
744107 747 1825659.5128978956
744202 702 3797054.1677634423
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2019/1.json
744103 5742 19401964.77965755
744101 5156 15501306.227195919
744102 3925 16683547.094795756
744105 3553 11588669.48032856
744104 2833 9141657.219605077
744211 1511 5794838.401831552
744202 1112 3613381.294736007
744107 1029 3592930.2975779255
744301 920 4652963.41114777
744112 802 1893718.6537822199
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2019/2.json
744104 6142 15625676.560883244
744103 5847 23751450.067206983
744101 4863 19061125.41121897
744102 4120 18948733.987097777
744105 3500 13418692.199162653
744202 1153 3619993.3910789257
744107 1124 2967445.3902032813
744211 1047 3168331.9917352106
744301 1007 4849284.51925976
744112 763 2928099.608406143
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2019/3.json
744103 5680 19906337.014255583
744101 5606 18745152.093515635
744104 4786 15754793.354826454
744102 3643 14572605.602745283
744105 3512 11767223.99688773
744202 1417 3875602.0982028744
744301 1402 6195496.621729916
744211 1118 2983697.449378184
744107 914 1988299.759710987
744112 833 2198831.6919406196
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2019/4.json
744104 6633 20626642.701508522
744101 5282 23247752.473849062
744103 4840 19792507.955761045
744105 3528 15302141.17488026
744102 3237 15350444.97320769
744202 1783 5800016.5561128855
744211 1596 7908264.721918669
744301 1549 7056478.928838715
744201 886 946768.0636478986
744107 777 3030368.911900454
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2020/1.json
744101 11793 58229349.02415232
744103 5870 22009443.073053975
744105 4635 16774043.311987936
744102 3820 14517706.12269676
744211 1837 8425387.79004211
744301 1819 6901162.107519586
744202 1794 5037742.395579022
744104 1302 5293130.290633954
744201 1157 1242638.821252932
744107 1043 2990354.4448547475
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2020/2.json
744101 11868 48293323.21851964
744103 10035 26197535.98945152
744105 9341 23203019.858980607
744102 6012 17786750.907515876
744202 3722 8924121.010762567
744107 2555 3980470.6853698147
744301 2275 9055232.527755566
744211 2045 3319717.6328789736
744205 1847 4459064.90732021
744104 1840 3334591.822304932
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2020/3.json
744101 24386 100439119.66860783
744103 21272 60332278.69396809
744105 17166 44061506.56273589
744102 13934 43077189.842844136
744202 5779 11975748.707876923
744107 4753 7628018.669464628
744104 3468 7353834.51320935
744112 3422 6067986.696111794
744301 3071 13352610.531559702
744205 2991 7535645.788593667
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2020/4.json
744103 46884 138264791.5489212
744101 40392 136401368.02166596
744105 34410 87838226.93633425
744102 26694 76348598.32238364
744202 10949 25543799.074759968
744107 9743 18083250.19055397
744104 7654 19126095.533284884
744112 7016 15890275.050448488
744205 5118 12002695.281042248
744201 5011 6777275.536669218
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2021/1.json
744101 55726 190830957.0606181
744103 47328 158404100.7854989
744105 35467 111571687.43195169
744102 23957 80750048.8238959
744211 10648 34956327.94105429
744202 10597 28127629.877961583
744107 8848 19627951.469969153
744104 8799 27854306.51949638
744112 7113 21084790.0528014
744301 5630 22671937.31314759
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2021/2.json
744101 73334 227585492.7414593
744103 66321 174752815.1688521
744105 52645 134835744.22049245
744102 34289 100890426.76234055
744202 16476 40647907.96960775
744107 14524 24690581.539094776
744104 11278 28333852.06159348
744211 10182 20377949.346094526
744112 9635 21637658.167199604
744301 8463 27666837.39688266
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2021/3.json
744101 116324 388328168.7639693
744103 84790 246433385.80990067
744105 67257 185238368.4767078
744102 43850 131239564.16909727
744202 19088 48475163.574293144
744107 16203 37962312.09641009
744104 14657 35301326.114471875
744112 11565 28491553.61094001
744301 11553 43464511.051198
744211 9655 19497765.257140517
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2021/4.json
744101 165719 533026207.9731797
744103 121613 372243734.27985656
744105 95028 281223411.7435058
744102 58258 174623253.47653326
744211 27938 94222862.10725296
744104 25662 69245386.0816525
744202 21913 67790798.04849821
744107 21397 52036029.9980372
744112 18915 55448543.43365714
744301 14553 47792330.70050094
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2022/1.json
744101 209941 615978080.6944855
744103 157230 399715980.1391735
744105 122716 321850608.7396423
744102 74883 193336549.94178736
744104 32471 72915521.83614868
744211 30272 86955570.58655271
744107 25379 58776727.62636636
744202 24022 68519268.77643085
744112 23471 55469783.6622991
744301 17630 56879992.28461884
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2022/2.json
744101 252722 702122365.3629664
744103 230746 561168775.5622396
744105 176252 415796516.6034926
744102 101551 240451609.192299
744104 47069 94335358.34017953
744211 40245 108788594.62847154
744107 36402 82851064.58195859
744112 32548 70178309.12885833
744202 27750 84587978.8405464
744301 26170 74485462.68044695
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2022/3.json
744104 497273 951370315.4090765
744103 259994 545653686.3062732
744101 213864 444967255.802143
744105 208055 438754611.5375265
744102 114416 239581586.790242
744107 40466 85492008.49477127
744112 38350 74030563.48358011
744211 37918 89671382.06901146
744202 29918 85509005.84576747
744301 27668 70002553.35288173
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2022/4.json
744104 684366 1309407988.2902
744103 304600 612929267.1773143
744105 258097 505662756.1128938
744101 243494 467192496.17391205
744102 134923 264371699.73904055
744211 56491 137253267.66612908
744107 54192 104539818.47127225
744112 46364 82461782.47749998
744202 34689 94217164.85909571
744301 33669 82466591.07632071
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2023/1.json
744103 503053 969594706.0
744105 418090 774570559.0
744101 403456 749508057.0
744102 222855 427240840.0
744104 118286 201531285.0
744211 107424 263885620.0
744107 92715 168098531.0
744112 76246 131598911.0
744202 59440 165959850.0
744301 55605 111713635.0
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2023/2.json
744103 597774 1119274409.0
744105 507585 916209552.0
744101 486154 824857096.0
744102 269165 458977445.0
744104 134785 205244167.0
744107 114795 194986633.0
744211 106510 222510323.0
744112 89784 147571191.0
744202 72315 211302035.0
744301 63841 134197959.0
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2023/3.json
744103 697625 1158992204.0
744105 594280 962825309.0
744101 561910 880223225.0
744102 301979 500512890.0
744104 144283 201467258.0
744107 126430 192271794.0
744211 122188 205773943.0
744112 102093 142609621.0
744202 81233 229651761.0
744301 72307 142757567.0
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2023/4.json
744103 817988 1376084403.0
744105 687868 1111327351.0
744101 665217 1030639279.0
744102 343773 550517935.0
744211 208914 434254474.0
744104 180753 276651786.0
744107 150575 215238085.0
744112 121589 178498997.0
744301 92294 197278662.0
744202 91113 233493969.0
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2024/1.json
744103 915265 1466185445.0
744105 788690 1238176536.0
744101 729163 1111938725.0
744102 410733 635568629.0
744211 242702 502855645.0
744104 198252 287097896.0
744107 175286 238542585.0
744112 136050 198931121.0
744202 110787 274596943.0
744301 96150 182352308.0
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2024/2.json
744103 1017612 1578925731.0
744105 893820 1374445615.0
744101 811341 1158296326.0
744102 457481 690786139.0
744211 224583 411320695.0
744107 215143 279183707.0
744104 203691 288479778.0
744112 149015 212749987.0
744202 133606 309640750.0
744301 103555 192116394.0
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2024/3.json
744103 1447958 2053970205.0
744105 693711 961929148.0
744102 687213 994056767.0
744104 617317 839095587.0
744101 397378 543823715.0
744106 209731 260739712.0
744211 197101 284906813.0
744107 179048 222331863.0
744202 155096 325950998.0
744301 117129 221810524.0
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andaman-&-nicobar-islands/2024/4.json
744103 1624936 2327920210.0
744105 788313 1111527475.0
744104 750691 1054506007.0
744102 745988 1083724002.0
744101 444657 622167677.0
744211 316142 549541741.0
744106 247889 331449895.0
744107 195688 249976872.0
744202 177499 343623904.0
744301 130704 238936987.0
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2018/1.json
517501 110496 163487278.84449506
520001 96883 170605900.5466873
515001 92754 133522310.75704184
517507 88132 127450018.2101582
516001 84644 131194265.5243713
518502 82421 68040306.13881023
530016 81891 140880970.0990568
520010 69581 119009921.97401813
516360 68340 101612118.88480642
518501 68193 81006512.71677604
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2018/2.json
517501 165506 305629373.15863353
518502 140893 127814123.87394845
515001 129798 285924993.6163615
517507 127731 243405277.90481398
520001 123176 271911611.0495833
516001 114806 242175477.6115077
530016 111874 235770318.03054443
520010 100630 220730389.6490364
516360 96619 197068813.60447282
518501 93442 163942778.22947574
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2018/3.json
518502 1300146 709765829.9649723
533437 421968 240766495.05853492
518501 296154 291247918.8462258
517501 295403 466133618.6014985
515001 276595 438158383.2247275
530016 234494 380410223.19526947
517507 233347 386563858.6898683
516259 220165 109844218.671292
520011 213275 291805923.00111276
520001 206435 371140000.30740225
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2018/4.json
518502 441662 332201263.2829269
517501 423357 714887920.0334857
530016 367619 575982481.3389585
515001 355695 651952970.9302757
517507 318300 594747982.0458119
530003 277131 356075793.85855436
516001 269798 572252390.1920383
520010 250261 492229977.1570112
530017 248725 326891428.60271376
518501 248520 357423401.5571966
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2019/1.json
530001 950821 1529039457.6419592
517501 922416 1244725311.4573965
520001 814616 1462807205.627422
530016 684611 960022481.5524917
517507 671661 1009128524.8128469
515001 609682 1009938283.8464416
518502 545426 389782596.9665674
530003 527667 590799502.8850918
530017 472914 531596255.9349663
520010 460133 774931063.0289192
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2019/2.json
530001 2602865 5218795715.70141
520001 1828617 3823390190.0922346
517501 949187 1669949938.5076957
522001 839909 1759418775.980979
530016 793798 1257915825.5688605
517507 760335 1412863012.2407691
515001 567306 1282118916.2094193
530003 520142 718170914.395836
520010 490697 973983824.5472903
530017 480905 650710126.3382195
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2019/3.json
530001 2944756 6693257653.901131
520001 1905190 4414503365.699517
517501 1434209 2203932856.2972074
530016 1196020 1658162548.562835
517507 1060513 1854927351.7366562
522001 1003916 2216532548.7258
515001 868052 1667826831.8650486
530003 858005 970993081.1712441
530017 799271 911939243.0618924
530026 711726 1095056835.9858122
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2019/4.json
530001 4185063 9160387223.4497
520001 2544877 5933007156.535349
517501 1920211 3073084029.9256625
530016 1591033 2295184224.145106
530026 1438154 2509394595.5414515
517507 1406768 2478459132.7705936
522001 1324202 2927313967.683236
515001 1202983 2376869516.684207
530003 1131832 1339103327.887921
530017 1084796 1266927471.3317952
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2020/1.json
530026 6695271 15258657486.862274
517501 2196548 3731404465.729061
530016 1661816 2593325339.0472875
517507 1554974 2719620696.0325623
515001 1346804 2696427930.6755033
530003 1159480 1519955258.5314608
524002 1125194 2653339803.95633
530017 1104748 1412381495.9440272
520010 1098395 2059547223.1742206
522001 1058410 2575723775.0488396
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2020/2.json
530026 4994637 12817902607.017586
517501 1708935 3203679955.4885287
517507 1575118 2854711069.441047
524002 1553283 3993963025.6852684
530016 1067022 1893629834.0393307
516001 1066066 2616099329.3322473
515001 1026587 2447755903.073549
518002 979822 2015820866.3250332
522001 963666 2678051229.473872
520002 956641 2767045048.1995325
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2020/3.json
524002 5194663 13718743729.17845
530026 4159532 10383207817.795242
517501 2735691 5544720473.076229
516001 2534360 6637577271.358326
517507 2306174 4594510974.325968
520002 2238996 6543183825.055463
530016 1921871 3560898943.243418
515001 1669413 4116758527.095812
522001 1625687 4701116488.838855
518002 1514873 3352462441.2241564
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2020/4.json
524002 5029692 12810644736.250324
530026 4235146 9849636860.464972
517501 4125544 7866883789.381668
517507 3420778 6749696775.855953
516001 3119905 8005247952.077286
530016 2981818 5591062751.070802
515001 2821800 6442101736.915546
518002 2219953 4809927717.539759
520010 2170458 4679865894.241622
530017 2027751 3252434512.586547
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2021/1.json
524002 7269657 16698428355.239132
530026 5875319 13567044097.312927
517501 4354325 8224302893.470669
520002 3591058 9183853695.408499
517507 3378549 6593121540.981036
530016 3144495 5679150412.005564
516001 2941623 7434205012.068323
515001 2815993 6225481722.602297
522001 2584588 6753205746.899624
520010 2291676 4716738889.930448
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2021/2.json
524002 11023032 25519404146.52658
530026 7850540 19042845773.20165
520002 5441708 14948864290.86964
517501 4614209 9215678010.439575
517507 3834825 7940105016.380435
522001 3427039 9832657321.439524
515001 3052771 7213837063.020088
530016 2892664 5705916880.595729
516001 2613562 7256266063.657529
518002 2553688 5906664130.524334
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2021/3.json
524002 10701326 23300508690.71216
530026 9780096 22841763578.29273
517501 5982442 11419848822.233982
520002 5320101 14633600592.216694
517507 4866065 9768221617.56348
522001 4242875 11355623168.660927
530016 4177023 7797927714.306906
515001 4040160 8752025049.046715
516001 3370675 8720115499.341372
520010 3206301 6832329071.6628275
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\transaction\country\india\state/andhra-pradesh/2021/4.json
524002 14158439 30358274591.367683
530026 10216678 24428085477.49295
517501 7246667 13514835187.056923
517507 5790910 11415016234.059563
520002 5716025 15397268124.171196
530016 5252680 9484946022.822403
522001 4989759 13298088500.28115
515001 4892740 10235401678.208153
520010 4198904 8551737728.052567
516001 4058071 10324818012.146276

,State,Year,Quarter,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar Islands,2018,1,744101,1622,2.769298e+06
1,Andaman & Nicobar Islands,2018,1,744103,1223,2.238042e+06
2,Andaman & Nicobar Islands,2018,1,744102,969,3.519060e+06
3,Andaman & Nicobar Islands,2018,1,744105,685,1.298561e+06
4,Andaman & Nicobar Islands,2018,1,744104,340,1.039715e+06
...,...,...,...,...,...,...
9994,West Bengal,2024,4,711101,6753348,1.049483e+10
9995,West Bengal,2024,4,700059,6662715,8.009476e+09
9996,West Bengal,2024,4,700039,6575693,9.018748e+09
9997,West Bengal,2024,4,734001,6432082,8.996529e+09
9998,West Bengal,2024,4,733134,6313560,1.050259e+10

In [11]:
# Path to the top user data
top_user_state_path=r"C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state"
top_user_state_list=os.listdir(top_user_state_path)

top_user_data={'State':[],'Year':[],'Quarter':[],'Pincodes':[],'RegisteredUsers':[]}

#using for loop to extract the path
for state in top_user_state_list:
  years=os.listdir(f"{top_user_state_path}/{state}")
  for year in years:
    quarter=os.listdir(f"{top_user_state_path}/{state}/{year}")
    for qtr in quarter:
      # Check if the entry is a json file
      if qtr.endswith('.json'):
        path=f"{top_user_state_path}/{state}/{year}/{qtr}"
        print(f"Processing file: {path}")

        #loding json file
        try: 
          with open(path,'r') as f:
             data=json.load(f)
          #print(data)

          #extracting data for pincodes"
          for i in data['data']['pincodes']:
             entityname=i['name']
             registeredusers=i['registeredUsers']
         
             top_user_data['State'].append(state)
             top_user_data['Year'].append(year)
             top_user_data['Quarter'].append(int(qtr.strip('.json')))
             top_user_data['Pincodes'].append(entityname)
             top_user_data['RegisteredUsers'].append(registeredusers)

        except KeyError:
            print(f"Skipping file due to missing keys: {path}")
        except FileNotFoundError:
            print(f"Skipping file not found: {path}")
        except Exception as e:
            print(f"An error occurred while processing {path}: {e}")

#creating dataframe
top_user_df=pd.DataFrame(top_user_data)
top_user_df  

#Formatting the 'State' column for consistency
top_user_df ["State"]=top_user_df ["State"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar Islands')
top_user_df ["State"]=top_user_df ["State"].str.replace("-"," ")  
top_user_df ["State"]=top_user_df ["State"].str.title()
top_user_df ["State"]=top_user_df ["State"].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')

top_user_df

Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2018/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2018/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2018/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2018/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2019/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2019/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2019/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2019/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2020/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andaman-&-nicobar-islands/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2018/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2018/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2018/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2018/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2019/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2019/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2019/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2019/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2020/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/andhra-pradesh/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2018/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2018/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2018/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2018/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2019/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2019/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2019/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2019/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2020/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/arunachal-pradesh/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2018/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2018/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2018/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2018/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2019/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2019/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2019/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2019/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2020/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/assam/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2018/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2018/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2018/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2018/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2019/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2019/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2019/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2019/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2020/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/bihar/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/chandigarh/2018/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/chandigarh/2018/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/chandigarh/2018/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/chandigarh/2018/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/chandigarh/2019/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/chandigarh/2019/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/chandigarh/2019/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/chandigarh/2019/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/chandigarh/2020/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/chandigarh/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\top\user\country\india\state/chandigarh/2020/3.json

                          State  Year  Quarter Pincodes  RegisteredUsers
0     Andaman & Nicobar Islands  2018        1   744103             1608
1     Andaman & Nicobar Islands  2018        1   744101             1108
2     Andaman & Nicobar Islands  2018        1   744105             1075
3     Andaman & Nicobar Islands  2018        1   744102             1006
4     Andaman & Nicobar Islands  2018        1   744104              272
...                         ...   ...      ...      ...              ...
9995                West Bengal  2024        4   733134           169596
9996                West Bengal  2024        4   700059           169448
9997                West Bengal  2024        4   711302           146034
9998                West Bengal  2024        4   700150           142151
9999                West Bengal  2024        4   711106           142077

[10000 rows x 5 columns]

In [12]:
# Path to the map insurance data (hover)
map_ins1_state_path=r"C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state"
map_ins1_state_list=os.listdir(map_ins1_state_path)

# Initialize columns for the dataframe
map_ins1_data = {
    'State': [], 'Year': [], 'Quarter': [],
    'district': [], 'latitude': [], 'longitude': [], 'metric': [] 
}

# Loop through files
for state in map_ins1_state_list:
    years = os.listdir(f"{map_ins1_state_path}/{state}")
    for year in years:
        quarters = os.listdir(f"{map_ins1_state_path}/{state}/{year}")
        for qtr in quarters:
            if not qtr.endswith('.json'):
                continue
            # Construct the file path
            path = f"{map_ins1_state_path}/{state}/{year}/{qtr}"
            print(f"Processing file: {path}")
            # Load JSON file
            try:
                with open(path, 'r') as f:
                    data = json.load(f)
                # Check if the expected keys exist
                columns = data['data']['data']['columns']
                rows = data['data']['data']['data']
                # Extracting data
                for row in rows:
                    record = dict(zip(columns, row))

                    map_ins1_data['State'].append(state)
                    map_ins1_data['Year'].append(year)
                    map_ins1_data['Quarter'].append(int(qtr.strip('.json')))
                    map_ins1_data['district'].append(record.get('label'))
                    map_ins1_data['latitude'].append(record.get('lat'))
                    map_ins1_data['longitude'].append(record.get('lng'))
                    map_ins1_data['metric'].append(record.get('metric'))
                    
            
            except KeyError as e:
                print(f"Skipping file due to missing key {e}: {path}")
            except FileNotFoundError:
                print(f"Skipping file not found: {path}")
            except Exception as e:
                print(f"An error occurred while processing {path}: {e}")

# Creating DataFrame
map_ins1_df = pd.DataFrame(map_ins1_data)
map_ins1_df     

#Formatting the 'State' column for consistency
map_ins1_df ["State"]=map_ins1_df ["State"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar Islands')
map_ins1_df ["State"]=map_ins1_df ["State"].str.replace("-"," ")  
map_ins1_df ["State"]=map_ins1_df ["State"].str.title()
map_ins1_df ["State"]=map_ins1_df ["State"].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')

map_ins1_df

Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andaman-&-nicobar-islands/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/andhra-pradesh/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/arunachal-pradesh/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/assam/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/bihar/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chandigarh/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2022/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2023/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2023/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2023/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2023/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2024/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2024/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2024/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/chhattisgarh/2024/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2020/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2020/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2020/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2021/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2021/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2021/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2021/4.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2022/1.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2022/2.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2022/3.json
Processing file: C:\Users\sathishkumar\OneDrive\Phonepe_dashboard\pulse\data\map\insurance\country\india\state/dadra-&-nagar-haveli-&-daman-&-diu/2022/4.json

,State,Year,Quarter,district,latitude,longitude,metric
0,Andaman & Nicobar Islands,2020,2,nicobars district,9.173490,92.812846,3.0
1,Andaman & Nicobar Islands,2020,2,south andaman district,11.665257,92.753094,2.0
2,Andaman & Nicobar Islands,2020,2,south andaman district,11.665446,92.733193,1.0
3,Andaman & Nicobar Islands,2020,3,south andaman district,11.653981,92.743142,8.0
4,Andaman & Nicobar Islands,2020,3,south andaman district,11.654075,92.723246,8.0
...,...,...,...,...,...,...,...
1043132,West Bengal,2024,4,paschim medinipur district,22.522693,87.475255,1.0
1043133,West Bengal,2024,4,paschim medinipur district,22.637723,87.226997,1.0
1043134,West Bengal,2024,4,bankura district,23.595769,86.907310,1.0
1043135,West Bengal,2024,4,alipurduar district,26.707859,89.611038,1.0
1043136,West Bengal,2024,4,alipurduar district,26.754551,89.469491,1.0

Step 3 : Pushing dataframe into sql

In [13]:
!pip install sqlalchemy psycopg2

Requirement already satisfied: sqlalchemy in c:\users\sathishkumar\onedrive\phonepe_dashboard\.venv\lib\site-packages (2.0.41)
Requirement already satisfied: psycopg2 in c:\users\sathishkumar\onedrive\phonepe_dashboard\.venv\lib\site-packages (2.9.10)
Requirement already satisfied: greenlet>=1 in c:\users\sathishkumar\onedrive\phonepe_dashboard\.venv\lib\site-packages (from sqlalchemy) (3.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sathishkumar\onedrive\phonepe_dashboard\.venv\lib\site-packages (from sqlalchemy) (4.14.1)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
from sqlalchemy import create_engine
import pandas as pd
import psycopg2

In [15]:
engine = create_engine('postgresql+psycopg2://postgres:MALATHI28@localhost:5432/phonepedb')

In [ ]:
#Pushing dataframe in sql
agg_ins_df.to_sql('agg_ins_table', con=engine, if_exists='replace', index=False)
agg_trans_df.to_sql('agg_trans_table', con=engine, if_exists='replace', index=False)
agg_user_df.to_sql('agg_user_table', con=engine, if_exists='replace', index=False)
map_ins_df.to_sql('map_ins_table', con=engine, if_exists='replace', index=False)
map_ins1_df.to_sql('map_ins1_table', con=engine, if_exists='replace', index=False)
map_trans_df.to_sql('map_trans_table', con=engine, if_exists='replace', index=False)
map_user_df.to_sql('map_user_table', con=engine, if_exists='replace', index=False)
top_ins_df.to_sql('top_ins_table', con=engine, if_exists='replace', index=False)
top_trans_df.to_sql('top_trans_table', con=engine, if_exists='replace', index=False)
top_user_df.to_sql('top_user_table', con=engine, if_exists='replace', index=False)

682

Step 4 :Writing sql queries

In [26]:
import pandas as pd
from db_connection import engine
import psycopg2

In [27]:
import sys
sys.path.append('C:/Users/sathishkumar/Downloads/pulse')  # Update to your folder path

from db_connection import engine

♦Bussiness Case study Analysis

Decoding Transaction Dynamics on PhonePe
Scenario
PhonePe, a leading digital payments platform, has recently identified significant variations in transaction behavior across states, quarters, and payment categories. While some regions and transaction types demonstrate consistent growth, others show stagnation or decline. The leadership team seeks a deeper understanding of these patterns to drive targeted business strategies.

In [28]:
#1.1 Top States by Total Transaction Amount
#Insight:Analyzes state-wise transaction performance from map data
query="""SELECT "State", 
 sum("Transaction_amount") as Total_transaction_amount
 FROM agg_trans_table
 GROUP BY "State"
 ORDER BY Total_transaction_amount desc;"""
state_transaction_df = pd.read_sql(query, engine)
state_transaction_df

                                       State  total_transaction_amount
0                                  Telangana              4.165596e+13
1                                  Karnataka              4.067872e+13
2                                Maharashtra              4.037420e+13
3                             Andhra Pradesh              3.466908e+13
4                              Uttar Pradesh              2.688521e+13
5                                  Rajasthan              2.634324e+13
6                             Madhya Pradesh              1.912528e+13
7                                      Bihar              1.790135e+13
8                                West Bengal              1.558416e+13
9                                     Odisha              1.226398e+13
10                                Tamil Nadu              1.193622e+13
11                                     Delhi              1.163752e+13
12                                   Gujarat              1.019291e+13
13                                   Haryana              9.645037e+12
14                                 Jharkhand              5.906646e+12
15                              Chhattisgarh              4.890472e+12
16                                     Assam              3.460792e+12
17                                    Kerala              3.076269e+12
18                                    Punjab              2.983078e+12
19                               Uttarakhand              1.916489e+12
20                           Jammu & Kashmir              1.184683e+12
21                          Himachal Pradesh              6.875374e+11
22                                       Goa              5.110212e+11
23                                Chandigarh              2.929066e+11
24                         Arunachal Pradesh              2.744350e+11
25                                Puducherry              2.373171e+11
26  Dadra and Nagar Haveli and Daman and Diu              2.017199e+11
27                                   Tripura              2.005834e+11
28                                   Manipur              1.862656e+11
29                                 Meghalaya              1.625439e+11
30                                  Nagaland              1.303586e+11
31                                    Sikkim              1.189454e+11
32                                    Ladakh              8.899462e+10
33                 Andaman & Nicobar Islands              7.066745e+10
34                                   Mizoram              4.610210e+10
35                               Lakshadweep              1.609321e+09

In [29]:
#1.2 Quarterly Growth of Transactions in Each State
#Insight: Observe transaction trends over time in each state for identifying consistent growth or decline.

query="""SELECT "State",
 "Year","Quarter",
 sum("Transaction_amount") as Total_transaction_amount
 FROM agg_trans_table
 GROUP BY "State", "Year", "Quarter";"""
state_quarterly_growth_df = pd.read_sql(query, engine)
state_quarterly_growth_df

,State,Year,Quarter,total_transaction_amount
0,Ladakh,2021,1,9.834198e+08
1,Haryana,2023,1,5.911506e+11
2,Dadra and Nagar Haveli and Daman and Diu,2024,4,2.394522e+10
3,Karnataka,2024,1,3.485249e+12
4,Himachal Pradesh,2020,1,7.419467e+09
...,...,...,...,...
1003,Telangana,2022,1,1.670638e+12
1004,Gujarat,2021,2,2.101621e+11
1005,Chandigarh,2018,1,6.134354e+08
1006,Arunachal Pradesh,2022,4,9.684910e+09
1007,Karnataka,2024,3,3.907203e+12

In [30]:
#1.3 Most Popular Transaction Type Nationally
#Insight:Highlights the transaction category (e.g., Recharge, P2P, Bills) that dominates usage

query="""SELECT "Transaction_type",
 sum("Transaction_count") as Total_transaction_count
 FROM agg_trans_table
 GROUP BY "Transaction_type"
ORDER BY Total_transaction_count DESC"""
transaction_type_df = pd.read_sql(query, engine)
transaction_type_df

           Transaction_type  total_transaction_count
0         Merchant payments             1.302388e+11
1     Peer-to-peer payments             8.503245e+10
2  Recharge & bill payments             1.959676e+10
3                    Others             2.620502e+08
4        Financial Services             1.542089e+08

In [31]:
#1.4 . States, Districts, and Quarters with Decline in Transactions
#Insight: Identifies states,district,year experiencing a drop in transaction volume, indicating potential issues or seasonal trends.
query="""SELECT 
    t1."State",
    t1."District",
    t1."Year",
    t1."Quarter" AS From_Quarter,
    t2."Quarter" AS To_Quarter,
    t1."Transaction_count" AS From_Count,
    t2."Transaction_count" AS To_Count
FROM map_trans_table t1
JOIN map_trans_table t2
  ON t1."State" = t2."State"
 AND t1."District" = t2."District"
 AND t1."Year" = t2."Year"
 AND t2."Quarter" = t1."Quarter" + 1
WHERE t2."Transaction_count" < t1."Transaction_count"
ORDER BY t1."State", t1."District", t1."Year", t1."Quarter";"""
decline_states_df = pd.read_sql(query, engine)  
decline_states_df

,State,District,Year,from_quarter,to_quarter,from_count,to_count
0,Andaman & Nicobar Islands,south andaman district,2019,2,3,28490,27421
1,Andhra Pradesh,anantapur district,2019,1,2,3891336,3578836
2,Andhra Pradesh,anantapur district,2022,2,3,46099366,45165363
3,Andhra Pradesh,chittoor district,2019,1,2,6486813,5983308
4,Andhra Pradesh,chittoor district,2022,2,3,67507661,65751781
...,...,...,...,...,...,...,...
1262,West Bengal,purulia district,2019,1,2,826372,638348
1263,West Bengal,purulia district,2020,1,2,1140216,980210
1264,West Bengal,south twenty four parganas district,2019,1,2,2381496,2092814
1265,West Bengal,uttar dinajpur district,2018,3,4,565131,546004
1266,West Bengal,uttar dinajpur district,2019,1,2,591162,540199

In [32]:
#1.5 Find patterns of declining user activity across quarters by district and state
#Insight: Identifies districts and states with decreasing user activity, helping to target retention efforts.

query="""WITH Quarter_Comparisons AS (
  SELECT 
    t1."State",
    t1."District",
    t1."Year",
    t1."Quarter" AS From_Quarter,
    t2."Quarter" AS To_Quarter,
    t1."Transaction_count" AS From_Count,
    t2."Transaction_count" AS To_Count
  FROM map_trans_table t1
  JOIN map_trans_table t2
    ON t1."State" = t2."State"
   AND t1."District" = t2."District"
   AND t1."Year" = t2."Year"
   AND t2."Quarter" = t1."Quarter" + 1
  WHERE t2."Transaction_count" < t1."Transaction_count"
)

SELECT 
  "State",
  "District",
  "Year",
  COUNT(*) AS Decline_Streaks
FROM Quarter_Comparisons
GROUP BY "State", "District", "Year"
HAVING COUNT(*) >= 2
ORDER BY Decline_Streaks DESC;"""
decline_activity_df = pd.read_sql(query, engine)
decline_activity_df

              State             District  Year  decline_streaks
0   Jammu & Kashmir      budgam district  2019                3
1   Jammu & Kashmir    anantnag district  2019                3
2   Jammu & Kashmir   ganderbal district  2019                3
3   Jammu & Kashmir      poonch district  2019                3
4   Jammu & Kashmir     pulwama district  2019                3
..              ...                  ...   ...              ...
82            Bihar  sheikhpura district  2019                2
83            Delhi     central district  2020                2
84            Delhi   new delhi district  2022                2
85          Gujarat       anand district  2019                2
86          Gujarat       kheda district  2019                2

[87 rows x 4 columns]

Device Dominance and User Engagement Analysis
Scenario
PhonePe aims to enhance user engagement and improve app performance by understanding user preferences across different device brands. The data reveals the number of registered users and app opens, segmented by device brands, regions, and time periods. However, trends in device usage vary significantly across regions, and some devices are disproportionately underutilized despite high registration numbers.

In [33]:
#2.1 Top Device Brands by Total Users
#Insight: Identifies the most popular device brands among users, which can inform marketing and product development strategies.
query="""SELECT "Device_Brand", SUM("Transaction_count") AS Total_Users
FROM agg_user_table
GROUP BY "Device_Brand"
ORDER BY Total_Users DESC;"""
top_device_brands_df = pd.read_sql(query, engine)
top_device_brands_df

   Device_Brand  total_users
0        Xiaomi  869562617.0
1       Samsung  671603711.0
2          Vivo  625415019.0
3          Oppo  420250245.0
4        Others  282950234.0
5        Realme  219973222.0
6         Apple   95947314.0
7      Motorola   73340734.0
8       OnePlus   63677211.0
9        Huawei   57129693.0
10       Lenovo   42564548.0
11        Tecno   12388623.0
12     Micromax   11132859.0
13      Infinix    5142870.0
14         Asus    4295498.0
15       Gionee    3082772.0
16         Lava    1530109.0
17   HMD Global     336632.0
18          Lyf       1271.0
19      COOLPAD         10.0

In [34]:
#2.2High App Opens but Low Registrations
#Insight: Identifies districts with high app engagement but low user registrations, indicating potential barriers to onboarding.
query="""SELECT "State", "District", "RegisteredUsers", "AppOpens"
FROM map_user_table
WHERE "RegisteredUsers" < 1000 AND "AppOpens" > 5000
ORDER BY "AppOpens" DESC;"""
low_registrations_df = pd.read_sql(query, engine)
low_registrations_df

                 State                District  RegisteredUsers  AppOpens
0    Arunachal Pradesh  dibang valley district              950   3376396
1    Arunachal Pradesh  dibang valley district              988   2759193
2      Jammu & Kashmir   muzaffarabad district              689   2388963
3    Arunachal Pradesh       shi yomi district              773   2183593
4    Arunachal Pradesh       shi yomi district              688   1962286
..                 ...                     ...              ...       ...
103  Arunachal Pradesh  pakke kessang district              296      5981
104  Arunachal Pradesh       shi yomi district              370      5847
105  Arunachal Pradesh  pakke kessang district              244      5099
106  Arunachal Pradesh          kamle district              323      5098
107            Manipur       pherzawl district              245      5039

[108 rows x 4 columns]

In [35]:
#2.3 Device Brands with Possible Decline
#Insight: Identifies device brands with decreasing user counts, which may indicate shifting user preferences or market trends.
query="""SELECT "Device_Brand","Year", "Quarter", 
SUM("Transaction_count") AS Total_Users
FROM agg_user_table
GROUP BY "Device_Brand", "Year", "Quarter"
ORDER BY Total_Users DESC;"""
device_decline_df = pd.read_sql(query, engine)  
device_decline_df

    Device_Brand  Year  Quarter  total_users
0         Xiaomi  2022        1   88426667.0
1         Xiaomi  2021        4   84820133.0
2         Xiaomi  2021        3   80749293.0
3           Vivo  2022        1   77224385.0
4         Xiaomi  2021        2   75948216.0
..           ...   ...      ...          ...
277   HMD Global  2020        2       5589.0
278   HMD Global  2020        1       1394.0
279          Lyf  2018        2        726.0
280          Lyf  2018        1        545.0
281      COOLPAD  2018        1         10.0

[282 rows x 4 columns]

In [36]:
#2.4 Device Brand Trends Over Quarters
#Insight: Analyzes how device brand popularity changes over time, helping to identify emerging trends
query="""SELECT "Device_Brand", "Year", "Quarter",
SUM("Transaction_count") AS Total_Users
FROM agg_user_table
GROUP BY "Device_Brand", "Year", "Quarter"
ORDER BY "Device_Brand", "Year", "Quarter";"""
device_trends_df = pd.read_sql(query, engine)   
device_trends_df

    Device_Brand  Year  Quarter  total_users
0          Apple  2018        1    1778928.0
1          Apple  2018        2    2236385.0
2          Apple  2018        3    2667940.0
3          Apple  2018        4    3288545.0
4          Apple  2019        1    3836258.0
..           ...   ...      ...          ...
277       Xiaomi  2021        1   71552898.0
278       Xiaomi  2021        2   75948216.0
279       Xiaomi  2021        3   80749293.0
280       Xiaomi  2021        4   84820133.0
281       Xiaomi  2022        1   88426667.0

[282 rows x 4 columns]

In [37]:
#2.5 Compare Engagement vs Registration
#Insight: Compares user engagement (app opens) with registration counts to identify potential gaps in user acquisition strategies.
query="""SELECT "State", 
sum("RegisteredUsers") AS Total_Registered_Users,
sum("AppOpens") AS Total_App_Opens
FROM map_user_table
GROUP BY "State"
ORDER BY Total_App_Opens DESC;"""
engagement_vs_registration_df = pd.read_sql(query, engine)
engagement_vs_registration_df

,State,total_registered_users,total_app_opens
0,Maharashtra,1.140138e+09,4.961642e+10
1,Rajasthan,5.557745e+08,4.850763e+10
2,Madhya Pradesh,4.706636e+08,3.970850e+10
3,Karnataka,7.336742e+08,3.834488e+10
4,Uttar Pradesh,9.423341e+08,3.323683e+10
5,Andhra Pradesh,5.567471e+08,2.472802e+10
6,Telangana,5.246205e+08,2.319777e+10
7,Gujarat,4.591547e+08,2.078042e+10
8,Tamil Nadu,5.064868e+08,1.699220e+10
9,Odisha,2.900053e+08,1.449392e+10
10,Bihar,4.461153e+08,1.360826e+10
11,Chhattisgarh,1.422910e+08,1.119041e+10
12,West Bengal,5.249644e+08,1.094382e+10
13,Jharkhand,1.692839e+08,1.090791e+10
14,Assam,1.118423e+08,9.436509e+09
15,Haryana,3.060221e+08,8.259126e+09
16,Punjab,1.714323e+08,5.142232e+09
17,Delhi,3.246081e+08,4.847106e+09
18,Kerala,2.047581e+08,3.968668e+09
19,Uttarakhand,8.693092e+07,3.413395e+09
20,Jammu & Kashmir,4.016253e+07,2.709558e+09
21,Himachal Pradesh,4.979982e+07,2.197083e+09
22,Arunachal Pradesh,8.046446e+06,1.117277e+09
23,Meghalaya,6.185282e+06,1.078449e+09
24,Tripura,1.386263e+07,6.717172e+08
25,Goa,1.743729e+07,5.283293e+08
26,Manipur,9.389131e+06,4.989851e+08
27,Nagaland,6.297675e+06,4.797297e+08
28,Mizoram,2.701061e+06,3.688843e+08
29,Ladakh,2.271369e+06,2.941118e+08
30,Sikkim,4.868004e+06,2.869701e+08
31,Dadra and Nagar Haveli and Daman and Diu,1.008020e+07,2.077349e+08
32,Puducherry,1.040715e+07,1.779624e+08
33,Chandigarh,1.285559e+07,1.722308e+08
34,Andaman & Nicobar Islands,1.842465e+06,1.700437e+08
35,Lakshadweep,1.426970e+05,5.048344e+06

In [38]:
#2.6 overall User Growth Trends
#Insight: Analyzes user growth trends over time, helping to identify periods of significant growth  
query="""SELECT "State", "Year", "Quarter",
SUM("RegisteredUsers") AS Total_Registered_Users
FROM map_user_table
GROUP BY "State", "Year", "Quarter"
ORDER BY "State", "Year", "Quarter";"""
user_growth_trends_df = pd.read_sql(query, engine)
user_growth_trends_df

                          State  Year  Quarter  total_registered_users
0     Andaman & Nicobar Islands  2018        1                  6740.0
1     Andaman & Nicobar Islands  2018        2                  9405.0
2     Andaman & Nicobar Islands  2018        3                 12149.0
3     Andaman & Nicobar Islands  2018        4                 15222.0
4     Andaman & Nicobar Islands  2019        1                 18596.0
...                         ...   ...      ...                     ...
1003                West Bengal  2023        4              30064546.0
1004                West Bengal  2024        1              31306843.0
1005                West Bengal  2024        2              32540397.0
1006                West Bengal  2024        3              33612828.0
1007                West Bengal  2024        4              34750181.0

[1008 rows x 4 columns]

Insurance Penetration and Growth Potential Analysis
Scenario
PhonePe has ventured into the insurance domain, providing users with options to secure various policies. With increasing transactions in this segment, the company seeks to analyze its growth trajectory and identify untapped opportunities for insurance adoption at the state level. This data will help prioritize regions for marketing efforts and partnerships with insurers

In [39]:
#3.1States with Low Insurance Adoption (untapped potential)
#Insight: Identifies states with low insurance adoption, helping to target awareness and marketing efforts.
query="""SELECT "State", SUM("Transaction_count") AS Total_Insurance_Count
FROM agg_ins_table
GROUP BY "State"
ORDER BY Total_Insurance_Count ASC;"""
low_insurance_adoption_df = pd.read_sql(query, engine)
low_insurance_adoption_df

                                       State  total_insurance_count
0                                Lakshadweep                  496.0
1                                     Ladakh                 3338.0
2                                    Mizoram                 3724.0
3                                    Manipur                 3731.0
4                                   Nagaland                 4745.0
5                                     Sikkim                 4896.0
6                          Arunachal Pradesh                10214.0
7                                  Meghalaya                10461.0
8                  Andaman & Nicobar Islands                12997.0
9   Dadra and Nagar Haveli and Daman and Diu                13792.0
10                                Chandigarh                22079.0
11                                   Tripura                25192.0
12                                Puducherry                27940.0
13                                       Goa                59872.0
14                          Himachal Pradesh                61790.0
15                           Jammu & Kashmir                78375.0
16                               Uttarakhand               124374.0
17                                    Punjab               180011.0
18                              Chhattisgarh               189517.0
19                                 Jharkhand               260827.0
20                                     Assam               262818.0
21                                    Odisha               318769.0
22                            Madhya Pradesh               487180.0
23                                     Bihar               536592.0
24                                   Gujarat               562595.0
25                                   Haryana               573738.0
26                                 Rajasthan               639684.0
27                                     Delhi               652514.0
28                            Andhra Pradesh               697769.0
29                                    Kerala               824235.0
30                               West Bengal               839715.0
31                                 Telangana               894342.0
32                             Uttar Pradesh              1139153.0
33                                Tamil Nadu              1215269.0
34                               Maharashtra              1815539.0
35                                 Karnataka              1957404.0

In [40]:
#3.2 Top States by Number of Insurance Transactions
#Insight: Identifies states with the highest number of insurance transactions, indicating strong market presence.
query="""SELECT "State", SUM("Transaction_count") AS Total_Insurance_Transactions
FROM agg_ins_table
GROUP BY "State"
ORDER BY Total_Insurance_Transactions DESC;"""
top_insurance_states_df = pd.read_sql(query, engine)
top_insurance_states_df

                                       State  total_insurance_transactions
0                                  Karnataka                     1957404.0
1                                Maharashtra                     1815539.0
2                                 Tamil Nadu                     1215269.0
3                              Uttar Pradesh                     1139153.0
4                                  Telangana                      894342.0
5                                West Bengal                      839715.0
6                                     Kerala                      824235.0
7                             Andhra Pradesh                      697769.0
8                                      Delhi                      652514.0
9                                  Rajasthan                      639684.0
10                                   Haryana                      573738.0
11                                   Gujarat                      562595.0
12                                     Bihar                      536592.0
13                            Madhya Pradesh                      487180.0
14                                    Odisha                      318769.0
15                                     Assam                      262818.0
16                                 Jharkhand                      260827.0
17                              Chhattisgarh                      189517.0
18                                    Punjab                      180011.0
19                               Uttarakhand                      124374.0
20                           Jammu & Kashmir                       78375.0
21                          Himachal Pradesh                       61790.0
22                                       Goa                       59872.0
23                                Puducherry                       27940.0
24                                   Tripura                       25192.0
25                                Chandigarh                       22079.0
26  Dadra and Nagar Haveli and Daman and Diu                       13792.0
27                 Andaman & Nicobar Islands                       12997.0
28                                 Meghalaya                       10461.0
29                         Arunachal Pradesh                       10214.0
30                                    Sikkim                        4896.0
31                                  Nagaland                        4745.0
32                                   Manipur                        3731.0
33                                   Mizoram                        3724.0
34                                    Ladakh                        3338.0
35                               Lakshadweep                         496.0

In [41]:
#3.3 State-District Quarterly Insurance Growth Rate
#Insight:Ideal for targeted marketing, partnerships, and investment decisions in rapidly growing regions.
query="""WITH previous_quarter AS (
    SELECT 
        "State", 
        "District", 
        CAST("Year" AS INT) AS "Year", 
        "Quarter", 
        "Transaction_count" AS prev_count
    FROM map_ins_table
),
current_quarter AS (
    SELECT 
        "State", 
        "District", 
        CAST("Year" AS INT) AS "Year", 
        "Quarter", 
        "Transaction_count" AS curr_count
    FROM map_ins_table
)
SELECT 
    curr."State",
    curr."District",
    curr."Year",
    curr."Quarter",
    prev.prev_count,
    curr.curr_count,
    ROUND(((curr.curr_count - prev.prev_count) * 100.0) / NULLIF(prev.prev_count, 0), 2) AS Growth_Percentage
FROM current_quarter curr
JOIN previous_quarter prev
  ON curr."State" = prev."State"
  AND curr."District" = prev."District"
  AND curr."Year" = prev."Year"
  AND curr."Quarter" = prev."Quarter" + 1
WHERE curr."Year" >= 2022  -- Now works correctly after casting
ORDER BY Growth_Percentage DESC
LIMIT 20;"""
insurance_growth_rate_df = pd.read_sql(query, engine)
insurance_growth_rate_df

,State,District,Year,Quarter,prev_count,curr_count,growth_percentage
0,Himachal Pradesh,lahul and spiti district,2023,2,1,21,2000.00
1,Arunachal Pradesh,east kameng district,2022,2,1,10,900.00
2,Manipur,jiribam district,2022,3,1,9,800.00
3,Mizoram,saitual district,2024,4,1,8,700.00
4,Mizoram,champhai district,2022,4,2,16,700.00
5,Nagaland,zunheboto district,2022,4,1,7,600.00
6,Arunachal Pradesh,upper subansiri district,2022,4,1,7,600.00
7,Mizoram,aizawl district,2022,3,34,232,582.35
8,Meghalaya,south west garo hills district,2022,3,2,13,550.00
9,Mizoram,mamit district,2022,2,1,6,500.00
10,Arunachal Pradesh,kurung kumey district,2023,3,1,6,500.00
11,Mizoram,kolasib district,2022,2,1,6,500.00
12,Manipur,imphal east district,2023,4,11,65,490.91
13,Arunachal Pradesh,dibang valley district,2024,2,1,5,400.00
14,Arunachal Pradesh,anjaw district,2022,4,1,5,400.00
15,Manipur,bishnupur district,2023,4,3,15,400.00
16,Manipur,noney district,2024,3,1,5,400.00
17,Dadra and Nagar Haveli and Daman and Diu,diu district,2024,2,5,24,380.00
18,Nagaland,tuensang district,2024,4,3,14,366.67
19,Lakshadweep,lakshadweep district,2023,4,12,53,341.67

In [42]:
#3.4state,district,quater wise insurance growth trajectory
#Insight: Analyzes insurance growth trends over time in each state and district, helping to identify successful markets and areas needing improvement.
query="""SELECT 
    curr."State",
    curr."District",
    curr."Year",
    curr."Quarter",
    curr."Transaction_count" AS Current_Transaction_Count,
    prev."Transaction_count" AS Previous_Transaction_Count,
    ROUND(
        ((curr."Transaction_count" - prev."Transaction_count") * 100.0) / NULLIF(prev."Transaction_count", 0), 2
    ) AS Growth_Percentage
FROM map_ins_table curr
JOIN map_ins_table prev
  ON curr."State" = prev."State"
 AND curr."District" = prev."District"
 AND curr."Year" = prev."Year"
 AND curr."Quarter" = prev."Quarter" + 1
ORDER BY Growth_Percentage DESC;"""
insurance_growth_trajectory_df = pd.read_sql(query, engine)
insurance_growth_trajectory_df

,State,District,Year,Quarter,current_transaction_count,previous_transaction_count,growth_percentage
0,Rajasthan,jaisalmer district,2020,3,1083,44,2361.36
1,Jharkhand,gumla district,2020,3,42,2,2000.00
2,Himachal Pradesh,lahul and spiti district,2023,2,21,1,2000.00
3,Bihar,sheohar district,2020,3,36,2,1700.00
4,Madhya Pradesh,dindori district,2020,3,46,3,1433.33
...,...,...,...,...,...,...,...
10065,Uttar Pradesh,gautam buddha nagar district,2024,3,5,9887,-99.95
10066,Tamil Nadu,thiruvallur district,2024,3,5,12220,-99.96
10067,Delhi,south east delhi district,2024,3,2,5596,-99.96
10068,Andhra Pradesh,spsr nellore district,2024,3,1,2708,-99.96
10069,Gujarat,ahmadabad district,2024,3,4,10341,-99.96

In [43]:
#3.5 High-Priority Regions for Insurance Growth
#Insight: Identifies regions with high potential for insurance growth based on transaction volume and user engagement.
query="""SELECT 
    "State", 
    "District",
    SUM("Transaction_count") AS Total_Insurance_Transactions,
    COUNT(DISTINCT CONCAT("Year", '-', "Quarter")) AS Active_Quarters,
    ROUND(SUM("Transaction_count") * 1.0 / COUNT(DISTINCT CONCAT("Year", '-', "Quarter")), 2) AS Avg_Transactions_Per_Quarter
FROM map_ins_table
GROUP BY "State", "District"
HAVING SUM("Transaction_count") > 10000  
ORDER BY Avg_Transactions_Per_Quarter DESC
LIMIT 15;"""
high_priority_insurance_df = pd.read_sql(query, engine)
high_priority_insurance_df

,State,District,total_insurance_transactions,active_quarters,avg_transactions_per_quarter
0,Karnataka,bengaluru urban district,1117691.0,19,58825.84
1,Maharashtra,pune district,396173.0,19,20851.21
2,Gujarat,ahmedabad district,30452.0,2,15226.00
3,Maharashtra,thane district,260578.0,19,13714.63
4,Tamil Nadu,chennai district,251081.0,19,13214.79
5,Uttar Pradesh,gautambuddha nagar district,23958.0,2,11979.00
6,Maharashtra,mumbai suburban district,211311.0,19,11121.63
7,Telangana,rangareddy district,206714.0,19,10879.68
8,Telangana,medchal malkajgiri district,178028.0,19,9369.89
9,Rajasthan,jaipur district,177296.0,19,9331.37
10,Telangana,hyderabad district,169470.0,19,8919.47
11,Haryana,gurugram district,168368.0,19,8861.47
12,West Bengal,north twenty four parganas district,155839.0,19,8202.05
13,Kerala,ernakulam district,146403.0,19,7705.42
14,Delhi,south east district,15290.0,2,7645.00

Transaction Analysis for Market Expansion
Scenario
PhonePe operates in a highly competitive market, and understanding transaction dynamics at the state level is crucial for strategic decision-making. With a growing number of transactions across different regions, the company seeks to analyze its transaction data to identify trends, opportunities, and potential areas for expansion.

In [44]:
#4.1  States with Fastest Quarterly Growth in Transactions
#Insight: Identifies states with the highest growth rates in transactions, indicating strong market dynamics.
query="""WITH curr AS (
  SELECT "State", CAST("Year" AS INT) AS Year, "Quarter", SUM("Transaction_count") AS curr_count
  FROM agg_trans_table
  GROUP BY "State", "Year", "Quarter"
),
prev AS (
  SELECT "State", CAST("Year" AS INT) AS Year, "Quarter", SUM("Transaction_count") AS prev_count
  FROM agg_trans_table
  GROUP BY "State", "Year", "Quarter"
)
SELECT 
  c."State", c.Year, c."Quarter",
  ROUND(((c.curr_count - p.prev_count) * 100.0) / NULLIF(p.prev_count, 0), 2) AS Growth_Percentage
FROM curr c
JOIN prev p 
  ON c."State" = p."State" 
  AND c.Year = p.Year 
  AND c."Quarter" = p."Quarter" + 1
WHERE c.Year = 2023
ORDER BY Growth_Percentage DESC
LIMIT 10;"""
fastest_growth_states_df = pd.read_sql(query, engine)
fastest_growth_states_df

               State  year  Quarter  growth_percentage
0            Manipur  2023        4             144.17
1             Ladakh  2023        2              87.83
2        Lakshadweep  2023        4              45.07
3    Jammu & Kashmir  2023        2              40.23
4             Sikkim  2023        2              29.94
5        Uttarakhand  2023        2              29.44
6  Arunachal Pradesh  2023        2              28.82
7   Himachal Pradesh  2023        2              28.42
8              Bihar  2023        4              25.90
9        Lakshadweep  2023        3              25.31

In [45]:
#4.2  Fastest Growing States by Quarter-over-Quarter Growth
#Insight: Analyzes the quarter-over-quarter growth of transactions in each state, helping to identify emerging markets.
query="""SELECT 
    curr."State",
    curr."Year",
    curr."Quarter",
    prev."Transaction_amount" AS Previous_Amount,
    curr."Transaction_amount" AS Current_Amount,
    ROUND(
        (
            (curr."Transaction_amount" - prev."Transaction_amount") * 100.0 / 
            NULLIF(prev."Transaction_amount", 0)
        )::numeric,
        2
    ) AS Growth_Percentage
FROM agg_trans_table curr
JOIN agg_trans_table prev
  ON curr."State" = prev."State"
  AND curr."Year" = prev."Year"
  AND curr."Quarter" = prev."Quarter" + 1
ORDER BY Growth_Percentage DESC
LIMIT 10;"""
fastest_growing_states_df = pd.read_sql(query, engine)
fastest_growing_states_df

,State,Year,Quarter,previous_amount,current_amount,growth_percentage
0,Andaman & Nicobar Islands,2018,4,1.481491e+03,8.100146e+07,5467464.31
1,Mizoram,2019,3,1.445538e+04,2.575382e+08,1781507.97
2,Arunachal Pradesh,2019,4,6.408911e+04,1.100137e+09,1716474.61
3,Lakshadweep,2018,2,5.907505e+02,5.757123e+06,974443.90
4,Andhra Pradesh,2024,4,3.049498e+08,2.723665e+12,893052.10
5,Manipur,2019,3,9.195502e+04,8.033356e+08,873518.05
6,Manipur,2020,2,3.541845e+05,2.980243e+09,841337.96
7,Andhra Pradesh,2024,2,3.162492e+08,2.545133e+12,804687.32
8,Manipur,2023,4,7.086020e+05,5.690075e+09,802900.18
9,Andhra Pradesh,2024,3,3.242144e+08,2.555369e+12,788072.75

In [46]:
#4.3 Underperforming States with Low Transaction Totals
#Insight: Identifies states with low transaction totals, indicating potential areas for improvement or market entry.
query="""SELECT "State", 
SUM("Transaction_amount") AS Total_Transaction_Amount
FROM "agg_trans_table"
GROUP BY "State"
ORDER BY Total_Transaction_Amount ASC;"""
underperforming_states_df = pd.read_sql(query, engine)
underperforming_states_df

                                       State  total_transaction_amount
0                                Lakshadweep              1.609321e+09
1                                    Mizoram              4.610210e+10
2                  Andaman & Nicobar Islands              7.066745e+10
3                                     Ladakh              8.899462e+10
4                                     Sikkim              1.189454e+11
5                                   Nagaland              1.303586e+11
6                                  Meghalaya              1.625439e+11
7                                    Manipur              1.862656e+11
8                                    Tripura              2.005834e+11
9   Dadra and Nagar Haveli and Daman and Diu              2.017199e+11
10                                Puducherry              2.373171e+11
11                         Arunachal Pradesh              2.744350e+11
12                                Chandigarh              2.929066e+11
13                                       Goa              5.110212e+11
14                          Himachal Pradesh              6.875374e+11
15                           Jammu & Kashmir              1.184683e+12
16                               Uttarakhand              1.916489e+12
17                                    Punjab              2.983078e+12
18                                    Kerala              3.076269e+12
19                                     Assam              3.460792e+12
20                              Chhattisgarh              4.890472e+12
21                                 Jharkhand              5.906646e+12
22                                   Haryana              9.645037e+12
23                                   Gujarat              1.019291e+13
24                                     Delhi              1.163752e+13
25                                Tamil Nadu              1.193622e+13
26                                    Odisha              1.226398e+13
27                               West Bengal              1.558416e+13
28                                     Bihar              1.790135e+13
29                            Madhya Pradesh              1.912528e+13
30                                 Rajasthan              2.634324e+13
31                             Uttar Pradesh              2.688521e+13
32                            Andhra Pradesh              3.466908e+13
33                               Maharashtra              4.037420e+13
34                                 Karnataka              4.067872e+13
35                                 Telangana              4.165596e+13

In [47]:
#4.4 States with High Transaction Counts but Low Amounts
#Insight: Identifies states with high transaction counts but low transaction amounts, indicating potential issues with transaction value.
query="""SELECT 
    "State",
    SUM("Transaction_count") AS total_transactions,
    SUM("Transaction_amount") AS total_amount,
    ROUND(SUM("Transaction_amount")::numeric / NULLIF(SUM("Transaction_count"), 0), 2) AS avg_transaction_value
FROM agg_trans_table
GROUP BY "State"
ORDER BY avg_transaction_value ASC;"""
low_value_states_df = pd.read_sql(query, engine)
low_value_states_df

,State,total_transactions,total_amount,avg_transaction_value
0,Dadra and Nagar Haveli and Daman and Diu,2.012184e+08,2.017199e+11,1002.49
1,Maharashtra,3.198521e+10,4.037420e+13,1262.28
2,Chhattisgarh,3.733644e+09,4.890472e+12,1309.84
3,Karnataka,3.097095e+10,4.067872e+13,1313.45
4,Uttarakhand,1.458837e+09,1.916489e+12,1313.71
5,Kerala,2.300898e+09,3.076269e+12,1336.99
6,Madhya Pradesh,1.407218e+10,1.912528e+13,1359.08
7,Delhi,8.495317e+09,1.163752e+13,1369.87
8,Himachal Pradesh,5.008106e+08,6.875374e+11,1372.85
9,Odisha,8.918527e+09,1.226398e+13,1375.11
10,Jharkhand,4.266421e+09,5.906646e+12,1384.45
11,Goa,3.649444e+08,5.110212e+11,1400.27
12,Puducherry,1.666053e+08,2.373171e+11,1424.43
13,Haryana,6.744901e+09,9.645037e+12,1429.97
14,Chandigarh,2.038553e+08,2.929066e+11,1436.84
15,Jammu & Kashmir,8.206027e+08,1.184683e+12,1443.67
16,Uttar Pradesh,1.852360e+10,2.688521e+13,1451.40
17,Gujarat,6.726865e+09,1.019291e+13,1515.25
18,Assam,2.262441e+09,3.460792e+12,1529.67
19,Tamil Nadu,7.796386e+09,1.193622e+13,1530.99
20,Rajasthan,1.710854e+10,2.634324e+13,1539.77
21,Telangana,2.617468e+10,4.165596e+13,1591.46
22,Bihar,1.094103e+10,1.790135e+13,1636.17
23,Tripura,1.208385e+08,2.005834e+11,1659.93
24,Punjab,1.772412e+09,2.983078e+12,1683.06
25,West Bengal,9.191500e+09,1.558416e+13,1695.50
26,Arunachal Pradesh,1.602234e+08,2.744350e+11,1712.83
27,Andaman & Nicobar Islands,3.970695e+07,7.066745e+10,1779.72
28,Sikkim,6.586084e+07,1.189454e+11,1806.01
29,Lakshadweep,8.839940e+05,1.609321e+09,1820.51
30,Andhra Pradesh,1.891870e+10,3.466908e+13,1832.53
31,Meghalaya,8.863542e+07,1.625439e+11,1833.85
32,Ladakh,3.934588e+07,8.899462e+10,2261.85
33,Mizoram,1.953575e+07,4.610210e+10,2359.88
34,Nagaland,5.476874e+07,1.303586e+11,2380.16
35,Manipur,7.335034e+07,1.862656e+11,2539.40

In [48]:
#4.5 Geographic Expansion Potential (Based on Map Data)
#Insight:Use map-based transactions to identify unexplored or rising areas of opportunity.
query="""SELECT "State", "Year", "Quarter", 
SUM("Transaction_amount") AS Geo_Transaction_Amount
FROM map_trans_table
GROUP BY "State", "Year", "Quarter"
ORDER BY Geo_Transaction_Amount DESC;"""
geo_expansion_potential_df = pd.read_sql(query, engine)
geo_expansion_potential_df

            State  Year  Quarter  geo_transaction_amount
0       Karnataka  2024        4            4.151820e+12
1     Maharashtra  2024        4            4.151028e+12
2       Karnataka  2024        3            3.907203e+12
3       Telangana  2024        4            3.859051e+12
4       Karnataka  2024        2            3.785035e+12
...           ...   ...      ...                     ...
1003  Lakshadweep  2019        1            8.786130e+06
1004  Lakshadweep  2018        2            6.187810e+06
1005  Lakshadweep  2018        4            4.463214e+06
1006  Lakshadweep  2018        3            4.339032e+06
1007  Lakshadweep  2018        1            1.928611e+06

[1008 rows x 4 columns]

User Engagement and Growth Strategy

Scenario
PhonePe seeks to enhance its market position by analyzing user engagement across different states and districts. With a significant number of registered users and app opens, understanding user behavior can provide valuable insights for strategic decision-making and growth opportunities.

In [49]:
#5.1 Top States by Engagement Rate
#Insight: Identifies states with the highest user engagement rates, helping to target marketing and retention efforts.
query="""SELECT 
    "State", "Year", "Quarter",
    ROUND(SUM("AppOpens")::numeric / NULLIF(SUM("RegisteredUsers"), 0), 2) AS Engagement_Rate
FROM map_user_table
GROUP BY "State", "Year", "Quarter"
ORDER BY Engagement_Rate DESC
LIMIT 10;"""
top_engagement_states_df = pd.read_sql(query, engine)
top_engagement_states_df

               State  Year  Quarter  engagement_rate
0          Meghalaya  2024        1           566.77
1          Meghalaya  2024        2           539.48
2          Meghalaya  2024        3           533.22
3            Mizoram  2024        3           488.05
4             Ladakh  2023        3           354.02
5             Ladakh  2024        3           353.22
6             Ladakh  2024        2           307.02
7  Arunachal Pradesh  2024        3           306.85
8            Mizoram  2024        1           304.58
9  Arunachal Pradesh  2024        1           297.68

In [50]:
#5.2 State-wise Brand Dominance
#Insight: Analyzes the dominance of device brands in each state, helping to identify regional preferences.
query="""SELECT 
    "State", "Device_Brand",
    ROUND(AVG("Percentage"):: numeric, 2) AS Avg_Brand_Share
FROM agg_user_table
GROUP BY "State", "Device_Brand"
ORDER BY Avg_Brand_Share DESC
LIMIT 15;"""
state_brand_dominance_df = pd.read_sql(query, engine)
state_brand_dominance_df

               State Device_Brand  avg_brand_share
0            Manipur       Xiaomi             0.46
1    Jammu & Kashmir       Xiaomi             0.35
2            Mizoram       Xiaomi             0.32
3             Sikkim      Samsung             0.31
4           Nagaland       Xiaomi             0.30
5   Himachal Pradesh       Xiaomi             0.29
6              Bihar       Xiaomi             0.29
7             Odisha       Xiaomi             0.28
8          Jharkhand       Xiaomi             0.28
9             Ladakh       Xiaomi             0.28
10       West Bengal       Xiaomi             0.27
11         Karnataka       Xiaomi             0.26
12     Uttar Pradesh       Xiaomi             0.26
13    Madhya Pradesh       Xiaomi             0.26
14         Telangana       Xiaomi             0.26

In [51]:
#5.3  Districts with High Users but Low Engagement
#Insight: Identifies districts with high user counts but low engagement, indicating potential issues with user retention or app usability.
query="""SELECT 
    "State", "District", "Year", "Quarter",
    SUM("RegisteredUsers") AS Total_Users,
    SUM("AppOpens") AS Total_App_Opens,
    ROUND(SUM("AppOpens")::numeric / NULLIF(SUM("RegisteredUsers"), 0), 2) AS Engagement_Rate
FROM map_user_table
GROUP BY "State", "District", "Year", "Quarter"
HAVING SUM("RegisteredUsers") > 1000 AND ROUND(SUM("AppOpens")::numeric / NULLIF(SUM("RegisteredUsers"), 0), 2) < 1
ORDER BY Engagement_Rate ASC;"""
low_engagement_districts_df = pd.read_sql(query, engine)
low_engagement_districts_df

,State,District,Year,Quarter,total_users,total_app_opens,engagement_rate
0,Odisha,nayagarh district,2019,1,95412.0,0.0,0.00
1,Haryana,mewat district,2018,3,53421.0,0.0,0.00
2,Jammu & Kashmir,kishtwar district,2018,1,1298.0,0.0,0.00
3,Maharashtra,beed district,2018,2,102259.0,0.0,0.00
4,Himachal Pradesh,hamirpur district,2018,3,27915.0,0.0,0.00
...,...,...,...,...,...,...,...
3469,Jammu & Kashmir,kupwara district,2019,4,33279.0,5525.0,0.17
3470,Jammu & Kashmir,budgam district,2019,4,41377.0,14190.0,0.34
3471,Jammu & Kashmir,ganderbal district,2019,4,13506.0,4644.0,0.34
3472,Jammu & Kashmir,pulwama district,2019,4,28336.0,9905.0,0.35
3473,Jammu & Kashmir,srinagar district,2019,4,65611.0,28258.0,0.43

In [52]:
#5.4 States with Fastest Growth in Registrations (Quarter-over-Quarter)
#Insight: Identifies states with the highest growth rates in user registrations, indicating successful user acquisition strategies.
query="""WITH prev_quarter AS (
    SELECT "State", "Year", "Quarter", SUM("RegisteredUsers") AS reg_prev
    FROM map_user_table
    GROUP BY "State", "Year", "Quarter"
),
curr_quarter AS (
    SELECT "State", "Year", "Quarter", SUM("RegisteredUsers") AS reg_curr
    FROM map_user_table
    GROUP BY "State", "Year", "Quarter"
)
SELECT 
    curr."State",
    curr."Year",
    curr."Quarter",
    ROUND(
        ((curr.reg_curr - prev.reg_prev)::numeric / NULLIF(prev.reg_prev, 0)) * 100, 2
    ) AS Growth_Percentage
FROM curr_quarter curr
JOIN prev_quarter prev
  ON curr."State" = prev."State"
  AND curr."Year" = prev."Year"
  AND curr."Quarter" = prev."Quarter" + 1
ORDER BY Growth_Percentage DESC
LIMIT 10;"""
fastest_growth_registrations_df = pd.read_sql(query, engine)
fastest_growth_registrations_df

                       State  Year  Quarter  growth_percentage
0            Jammu & Kashmir  2024        3              82.54
1                    Manipur  2018        2              53.90
2  Andaman & Nicobar Islands  2024        3              53.05
3          Arunachal Pradesh  2018        2              52.98
4                    Tripura  2018        2              51.15
5                      Assam  2024        3              49.22
6                   Nagaland  2018        2              48.84
7            Jammu & Kashmir  2018        2              48.28
8                      Assam  2018        2              48.23
9                West Bengal  2018        2              47.18

In [53]:
#5.5 Most Popular Device Brands (All India)
#Insight: Identifies the most popular device brands among users across India, helping to inform marketing and product strategies.
query="""SELECT 
    "Device_Brand",
    SUM("Transaction_count") AS Total_Users,
    ROUND(AVG("Percentage"):: numeric, 2) AS Avg_Usage_Share
FROM agg_user_table
GROUP BY "Device_Brand"
ORDER BY Total_Users DESC
LIMIT 10;"""
popular_device_brands_df = pd.read_sql(query, engine)
popular_device_brands_df

  Device_Brand  total_users  avg_usage_share
0       Xiaomi  869562617.0             0.26
1      Samsung  671603711.0             0.19
2         Vivo  625415019.0             0.17
3         Oppo  420250245.0             0.12
4       Others  282950234.0             0.09
5       Realme  219973222.0             0.06
6        Apple   95947314.0             0.03
7     Motorola   73340734.0             0.02
8      OnePlus   63677211.0             0.02
9       Huawei   57129693.0             0.02

In [54]:
#5.6 Top 10 States with High User Engagement (App Opens per Registered User)
#Insight: Identifies states with high user engagement, measured by app opens per registered user, helping to target retention efforts.
query="""SELECT 
    "State",
    SUM("RegisteredUsers") AS Total_Registered_Users,
    SUM("AppOpens") AS Total_App_Opens,
    ROUND(SUM("AppOpens")::numeric / NULLIF(SUM("RegisteredUsers"), 0), 2) AS App_Open_Rate
FROM map_user_table
GROUP BY "State"
HAVING SUM("RegisteredUsers") > 100000  -- Optional threshold for meaningful data
ORDER BY App_Open_Rate DESC
LIMIT 10;"""
high_engagement_states_df = pd.read_sql(query, engine)
high_engagement_states_df

,State,total_registered_users,total_app_opens,app_open_rate
0,Meghalaya,6185282.0,1.078449e+09,174.36
1,Arunachal Pradesh,8046446.0,1.117277e+09,138.85
2,Mizoram,2701061.0,3.688843e+08,136.57
3,Ladakh,2271369.0,2.941118e+08,129.49
4,Andaman & Nicobar Islands,1842465.0,1.700437e+08,92.29
5,Rajasthan,555774493.0,4.850763e+10,87.28
6,Assam,111842317.0,9.436509e+09,84.37
7,Madhya Pradesh,470663624.0,3.970850e+10,84.37
8,Chhattisgarh,142291017.0,1.119041e+10,78.64
9,Nagaland,6297675.0,4.797297e+08,76.18